### ISSUE TITLE
Testing the app shouldn't require write permissions to /var/

### ISSUE THREAD

**Issue by ehartsuyker** [freedomofpress/securedrop#1193]
```
heartsucker@archimedes:~/code/freedom-of-the-press/securedrop/securedrop (babel-ascii)$ ./manage.py test
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    from db import db_session, Journalist
  File "/Users/heartsucker/code/freedom-of-the-press/securedrop/securedrop/db.py", line 26, in <module>
    import crypto_util
  File "/Users/heartsucker/code/freedom-of-the-press/securedrop/securedrop/crypto_util.py", line 56, in <module>
    gpg = gnupg.GPG(binary='gpg2', homedir=config.GPG_KEY_DIR, use_agent=True)
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/gnupg.py", line 127, in __init__
    use_agent=use_agent,)
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/_meta.py", line 137, in __init__
    self.homedir = home if home else _util._conf
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/_util.py", line 567, in __set__
    getattr(obj, self.fset.__name__)(value)
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/_meta.py", line 378, in _homedir_setter
    raise RuntimeError(ae.message)
RuntimeError: Homedir '/var/lib/securedrop/keys' needs read/write permissions
```

**Comment by garrettr** [comment]
You should always be running SecureDrop in one of the virtualized test environments. It is not intended to work anywhere else. You should read the [Developers Getting Started Guide](https://docs.securedrop.org/en/latest/development/getting_started.html)!
