### ISSUE TITLE
manage.py is can't find gpg2

### ISSUE THREAD

**Issue by ehartsuyker** [freedomofpress/securedrop#1194]
```
heartsucker@archimedes:~/code/freedom-of-the-press/securedrop/securedrop (babel-ascii)$ ./manage.py test
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    from db import db_session, Journalist
  File "/Users/heartsucker/code/freedom-of-the-press/securedrop/securedrop/db.py", line 26, in <module>
    import crypto_util
  File "/Users/heartsucker/code/freedom-of-the-press/securedrop/securedrop/crypto_util.py", line 56, in <module>
    gpg = gnupg.GPG(binary='gpg2', homedir=config.GPG_KEY_DIR, use_agent=True)
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/gnupg.py", line 127, in __init__
    use_agent=use_agent,)
  File "/Users/heartsucker/virtual-envs/securedrop/lib/python2.7/site-packages/gnupg/_meta.py", line 169, in __init__
    raise RuntimeError(ae.message)
RuntimeError: Could not find binary gpg2
heartsucker@archimedes:~/code/freedom-of-the-press/securedrop/securedrop (babel-ascii)$ brew
heartsucker@archimedes:~/code/freedom-of-the-press/securedrop/securedrop (babel-ascii)$ which gpg2
/usr/local/bin/gpg2
```

**Comment by garrettr** [comment]
Same as https://github.com/freedomofpress/securedrop/issues/1193#issuecomment-155485723.
