### ISSUE TITLE
GPG error in test suite on dev VM

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#1350]
Env:
```
heartsucker@pythagoras:~/code/freedom-of-press/securedrop (sass)$ uname -a
Linux pythagoras 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u2 (2016-06-25) x86_64 GNU/Linux
heartsucker@pythagoras:~/code/freedom-of-press/securedrop (sass)$ VBoxManage --version
4.3.36_Debianr105129
heartsucker@pythagoras:~/code/freedom-of-press/securedrop (sass)$ vagrant --version
Vagrant 1.8.4
```

Running the test suite output this:

```
vagrant@development:/vagrant/securedrop$ ./manage.py test
============================ test session starts =============================
platform linux2 -- Python 2.7.6 -- py-1.4.26 -- pytest-2.6.4
plugins: cov
collected 62 items 

requirements/test-requirements.txt .
tests/test_journalist.py ........
tests/test_single_star.py ......
tests/test_unit_integration.py ...........
tests/test_unit_journalist.py .................
tests/test_unit_source.py .................
tests/test_unit_store.py ..Exception in thread Thread-732:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 541, in _read_response
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'


-------------- coverage: platform linux2, python 2.7.6-final-0 ---------------
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
config.py                                         39      2    95%
crypto_util.py                                    81     10    88%
db.py                                            237     61    74%
journalist.py                                    390    132    66%
manage.py                                        132    132     0%
management/__init__.py                             1      1     0%
management/run.py                                 57     57     0%
request_that_secures_file_uploads.py              10      1    90%
secure_tempfile.py                                43      4    91%
source.py                                        241     43    82%
store.py                                          84     17    80%
template_filters.py                               32     13    59%
version.py                                         1      0   100%
worker.py                                          7      0   100%
------------------------------------------------------------------
TOTAL                                           1355    473    65%

========================= 62 passed in 26.28 seconds =========================
```

There is some sort of of `python-gnupug` `ValueError` raised, but the test doesn't fail. This looks suspicious.

**Comment by fowlslegs** [comment]
See https://github.com/freedomofpress/securedrop/issues/618#issuecomment-60293098 https://github.com/freedomofpress/securedrop/issues/618#issuecomment-60293098. I don't think this is an actual error in the sense that something went wrong, rather just an incompatibility with how our test suite runs and python-gnupg's use of daemon threads.

**Comment by garrettr** [comment]
@fowlslegs hit the nail on the head. The tests are not actually failing, but (according to my current theory, explained in the links provided in https://github.com/freedomofpress/securedrop/issues/1350#issuecomment-230128407) they are triggering long-running GPG operations (e.g. key generation) which complete after the test process that launched them has terminated, which triggers the errors you see. They are annoying, but harmless.

Since this is already tracked in #844, closing this as a duplicate.
