### ISSUE TITLE
gnupg exception in tests.py

### ISSUE THREAD

**Issue by diracdeltas** [freedomofpress/securedrop#138]
I suspect that async crypto.genkeypair in source.py/submit is returning after teardown has happened. \_block\_on\_reply\_keypair_gen() presumably fixes this, but I consistently get: 
```
(deaddrop)yan@ok-computer:~/deaddrop/modules/deaddrop/files/deaddrop$ python test.py
test_reply (__main__.TestIntegration) ... ok
test_submit_file (__main__.TestIntegration)
When a source creates an account, test that a new entry appears in the journalist interface ... ok
test_submit_message (__main__.TestIntegration)
When a source creates an account, test that a new entry appears in the journalist interface ... ok
Exception in thread Thread-8371:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yan/envs/deaddrop/local/lib/python2.7/site-packages/gnupg.py", line 736, in _read_response
    result.handle_status(keyword, value)
  File "/home/yan/envs/deaddrop/local/lib/python2.7/site-packages/gnupg.py", line 542, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'

test_index (__main__.TestJournalist) ... ok
test_create (__main__.TestSource) ... ok
test_generate (__main__.TestSource) ... ok
test_index (__main__.TestSource)
Test that the landing page loads and looks how we expect ... ok
test_login (__main__.TestSource) ... ok
test_regenerate_invalid_lengths (__main__.TestSource)
If the codename length is invalid, it should return 403 Forbidden ... ok
test_regenerate_valid_lengths (__main__.TestSource)
Make sure we can regenerate all valid length codenames ... ok
test_submit_both (__main__.TestSource) ... ok
test_submit_file (__main__.TestSource) ... ok
test_submit_message (__main__.TestSource) ... ok
test_verify (__main__.TestStore)Exception in thread Thread-12798:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/yan/envs/deaddrop/local/lib/python2.7/site-packages/gnupg.py", line 736, in _read_response
    result.handle_status(keyword, value)
  File "/home/yan/envs/deaddrop/local/lib/python2.7/site-packages/gnupg.py", line 542, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'

 ... ok

----------------------------------------------------------------------
Ran 14 tests in 727.748s

OK
```

**Comment by garrettr** [comment]
I still see `ValueError: Unknown status message: u'ERROR'` from python-gnupg sometimes, but it no longer causes tests to fail.
