### ISSUE TITLE
Exception thrown when submitting document

### ISSUE THREAD

**Issue by casey-bowman** [freedomofpress/securedrop#1459]
Virtual environment: develop
OS: mac 10.11.6
Ansible: 1.8.4
Virtualenv: 15.0.3
Python: 2.7.12
Vagrant: 1.8.6
Tor Browser: 6.0.5

When submitting a short .txt document and a short message, an exception was thrown. Jen was here at the Aaron Swartz Hackathon and recommended that I try again after restarting the Tor Browser and destroying the vagrant box. Again I saw this exception when trying to submit my first document.

vagrant@development:/vagrant/securedrop$ ./manage.py run

 => Source Interface <= 

 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
 * Restarting with stat

 => Document Interface <= 

 * Running on http://0.0.0.0:8081/ (Press CTRL+C to quit)
 * Restarting with stat

 => Source Interface <= 

 * Debugger is active!
 * Debugger pin code: 294-535-668

 => Document Interface <= 

 * Debugger is active!
 * Debugger pin code: 294-535-668

 => Source Interface <= 

10.0.2.2 - - [06/Nov/2016 02:38:45] "GET / HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /static/gen/source.css?f51c01da HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /static/i/no16-global.png HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /static/i/no16.png HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /static/i/logo.png HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /static/fonts/fontawesome-webfont.woff?v=4.1.0 HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:45] "GET /favicon.ico HTTP/1.1" 404 -
10.0.2.2 - - [06/Nov/2016 02:38:48] "GET /generate HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:38:48] "GET /static/i/favicon.png HTTP/1.1" 200 -
10.0.2.2 - - [06/Nov/2016 02:39:00] "POST /create HTTP/1.1" 302 -
10.0.2.2 - - [06/Nov/2016 02:39:00] "GET /lookup HTTP/1.1" 200 -
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 216, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 247, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer

**Comment by fowlslegs** [comment]
I don't think anyone has seen this bug before or since... I'm going to close this issue, but please do re-open if it's persisted for you @casey-bowman, or anyone who might run into it in the future.
