### ISSUE TITLE
Improve Admin-facing messaging in `securedrop-admin` script

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#1806]
# Feature request

## Description

The new `securedrop-admin` script brought in with #1781 could be made more informative during run for first-time Admins. Since the various stages of the script take a long time to run—e.g. roughly 10 minutes for the apt installs—it's vital to display progress to Admins, otherwise it looks a lot like the script hung.

We'll be running this script a lot during QA ramping up to the 0.4 release, so tracking changes targeting that tool in this issue, to be implemented in the near future. 

## Examples
* [x] The apt install task tasks nearly 10 minutes, and displays no messages during that run time:
```
$ ./securedrop-admin setup
INFO: Installing dependencies. You'll be prompted for the temporary Tails root credentials. This was set on boot-up screen
[sudo] password for amnesia: 
dpkg-preconfigure: unable to re-open stdin: No such file or directory
INFO: Setting up virtualenv
```

* [x] The message `dpkg-preconfigure: unable to re-open stdin: No such file or directory` always displays during the apt install task. No explanation for the warning message is provided, so it's unclear whether the operation completed successfully.

* [x] Tails tries to update packages automatically, and we can detect the apt lock error message and provide a better failure mode than displaying the traceback:

```
$ ./securedrop-admin setup
INFO: Installing dependencies. You'll be prompted for the temporary Tails root credentials. This was set on boot-up screen
[sudo] password for amnesia: 
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
Traceback (most recent call last):
  File "./securedrop-admin", line 164, in <module>
    args.func(args)
  File "./securedrop-admin", line 68, in envsetup
    libpython2.7-dev"]))
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['sudo', 'su', '-c', 'apt-get update &&                                             apt-get install -y                                             python-virtualenv                                             python-pip                                             ccontrol                                             virtualenv                                             libffi-dev                                             libssl-dev                                             libpython2.7-dev']' returned non-zero exit status 100
```

* [ ] Since the apt tasks take the longest of any step, we can break up the apt update and apt install tasks and provide messaging in between, as a progress indicator.

## User Stories
As an Admin, I want to know what the script is doing while it executes. More informative messaging (currently hidden under the `-v` flag) by default would be helpful.

As an Admin, I want to be able to make an informed decision about whether the script I'm running has hung. Under Tails, networking can sometimes be problematic, so a script that runs a long time and displays nothing to stdout can be confusing.

**Comment by conorsch** [comment]
>  Since the apt tasks take the longest of any step, we can break up the apt update and apt install tasks and provide messaging in between, as a progress indicator.

Skipping this idea, since then we'd have to prompt for the Tails admin password and pass it in to multiple process calls. Using the current `&&` approach means we only have a single called process for the apt installation tasks, and the real-time output while those commands run is sufficiently clear messaging about what's happening.
