### ISSUE TITLE
./securedrop-admin setup cryptic failure when the DNS does not resolve on tails-3.0

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1834]
# Bug

## Description

./securedrop-admin setup fails with no useful information when the DNS can't resolve

## Steps to Reproduce

point the DNS to something that does not work and run
./securedrop-admin setup

## Expected Behavior

A message that is related to the error (i.e. DNS resolution failure)

## Actual Behavior

Running the command manually shows useful information that is hidden by ./securedrop-admin (**1497630182 ERROR torsocks[3825]: Unable to resolve**)

<pre>
mnesia@amnesia:~/Persistent/securedrop$ torify virtualenv $(pwd)/.venv
Running virtualenv with interpreter /usr/bin/python2
1497630181 WARNING torsocks[3823]: [syscall] Unsupported syscall number 217. Denying the call (in tsocks_syscall() at syscall.c:488)
New python executable in /home/amnesia/Persistent/securedrop/.venv/bin/python2
Not overwriting existing python script /home/amnesia/Persistent/securedrop/.venv/bin/python (you must use /home/amnesia/Persistent/securedrop/.venv/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /home/amnesia/Persis...op/.venv/bin/python2 - setuptools pkg_resources pip wheel:
  Collecting setuptools
1497630182 ERROR torsocks[3825]: Unable to resolve. Status reply: 4 (in socks5_recv_resolve_reply() at socks5.c:683)
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/amnesia/Persistent/securedrop/.venv/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/amnesia/Persis...op/.venv/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
</pre>

**Comment by conorsch** [comment]
Related: #1806. More exception handling throughout the securedrop-admin script strikes me as a Good Thing™.

**Comment by conorsch** [comment]
Handling this exception via the CalledProcessError that gets raised from the subprocess call (not included in the OP), and providing a user-friendly message about checking the network connection. Will resolve along with changes for #1806.
