### ISSUE TITLE
./securedrop-admin sdconfig Exception: You must run the configure playbook.

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#1836]
# Bug

## Description

Following instructions at docs/install.rst and reaching the step 

./securedrop-admin sdconfig

fails with Exception: You must run the configure playbook.

## Steps to Reproduce

Follow docs/install.rst

## Expected Behavior

It succeeds

## Actual Behavior

<pre>
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin sdconfig
ERROR! Attempted to execute "inventory-dynamic" as inventory script: Inventory script (inventory-dynamic) had an execution error: Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/install_files/ansible-base/inventory-dynamic", line 138, in <module>
    inventory = build_inventory()
  File "/home/amnesia/Persistent/securedrop/install_files/ansible-base/inventory-dynamic", line 119, in build_inventory
    } for h in SECUREDROP_SUPPORTED_HOSTNAMES
  File "/home/amnesia/Persistent/securedrop/install_files/ansible-base/inventory-dynamic", line 119, in <dictcomp>
    } for h in SECUREDROP_SUPPORTED_HOSTNAMES
  File "/home/amnesia/Persistent/securedrop/install_files/ansible-base/inventory-dynamic", line 80, in lookup_ssh_address
    ssh_address = lookup_local_ipv4_address(hostname)
  File "/home/amnesia/Persistent/securedrop/install_files/ansible-base/inventory-dynamic", line 41, in lookup_local_ipv4_address
    raise Exception(msg)
Exception: You must run the configure playbook.
 
Traceback (most recent call last):
  File "./securedrop-admin", line 164, in <module>
    args.func(args)
  File "./securedrop-admin", line 50, in sdconfig
    cwd=ANSIBLE_PATH, env=os.environ.copy())
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/amnesia/Persistent/securedrop/./install_files/ansible-base/configure']' returned non-zero exit status 1
</pre>

**Comment by conorsch** [comment]
Ah, I see what's causing this: the dynamic-inventory script is trying to be helpful, saying there's no vars config yet, so we can't run the playbooks. That's true, but the whole point of the `sdconfig` subcommand is to _create_ the vars, so the warning is out of place.

The solution is to pass `-i /dev/null` to the `./configure` script's playbook invocations, so that the dynamic inventory script is _not_ read when setting up the vars.

**Comment by dachary** [comment]
thanks for looking into this quickly ! I can't really usefully comment on the solution since I started learning ansible today :-)
