### ISSUE TITLE
sass install failing in local development VM and CI

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#1971]
## Description

A few hours prior to this issue being posted the provisioning of local development VMs and CI builds on `develop` and `release/0.4` started failing. Around the same time the failures began occurring, sass 3.5 was released.

## Steps to Reproduce

`vagrant up development`

## Expected Behavior

The provisioning completes without failures.

## Actual Behavior

The provisioning started failing at the "Install sass Ruby gem" task:

```TASK [development : Install sass Ruby gem] *************************************
fatal: [development]: FAILED! => {"changed": false, "cmd": "/usr/bin/gem install --version 3.5.0 --include-dependencies --no-user-install --no-rdoc --no-ri sass", "failed": true, "msg": "ERROR:  Error installing sass:\n\tERROR: Failed to build gem native extension.\n\n        /usr/bin/ruby1.9.1 extconf.rb\n/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)\n\tfrom /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'\n\tfrom extconf.rb:4:in `<main>'\n\n\nGem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.18 for inspection.\nResults logged to /var/lib/gems/1.9.1/gems/ffi-1.9.18/ext/ffi_c/gem_make.out", "rc": 1, "stderr": "ERROR:  Error installing sass:\n\tERROR: Failed to build gem native extension.\n\n        /usr/bin/ruby1.9.1 extconf.rb\n/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)\n\tfrom /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'\n\tfrom extconf.rb:4:in `<main>'\n\n\nGem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.18 for inspection.\nResults logged to /var/lib/gems/1.9.1/gems/ffi-1.9.18/ext/ffi_c/gem_make.out\n", "stderr_lines": ["ERROR:  Error installing sass:", "\tERROR: Failed to build gem native extension.", "", "        /usr/bin/ruby1.9.1 extconf.rb", "/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)", "\tfrom /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'", "\tfrom extconf.rb:4:in `<main>'", "", "", "Gem files will remain installed in /var/lib/gems/1.9.1/gems/ffi-1.9.18 for inspection.", "Results logged to /var/lib/gems/1.9.1/gems/ffi-1.9.18/ext/ffi_c/gem_make.out"], "stdout": "INFO:  `gem install -y` is now default and will be removed\nINFO:  use --ignore-dependencies to install only the gems you list\nBuilding native extensions.  This could take a while...\n", "stdout_lines": ["INFO:  `gem install -y` is now default and will be removed", "INFO:  use --ignore-dependencies to install only the gems you list", "Building native extensions.  This could take a while..."]} 
```

## Comments

We should probably fix by pinning the version of the sass gem in `ansible-base/roles/development/tasks/main.yml` to the same version [pinned in the build role](353e026628acf11f9f904ac8cc1adafd40c1dd8b), 3.4.23.

**Comment by redshiftzero** [comment]
Relevant: #1594
