### ISSUE TITLE
Clean up Travis CI config

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/securedrop#2216]
# Feature request

## Description

The Travis CI config (`.travis.yml`) has a number of lines that have been present for a long time, and may no longer be necessary:

* [x] Stop using `sudo` to run tests
* [x] Don't start redis twice
* [x] Remove urandom setup
* [x] Linting should run before the dev playbook
* [ ] Remove conditional logic on SASS gem from dev config

Some may indeed still be necessary, but we have little documentation, even in git history, as to why, so the documentation base should be built up in case we need to keep any of the approach outlined above.

## User Stories

As a SecureDrop developer, I want the CI to be effective and informative, not a cauldron of best guesses to get the tests to pass.

**Comment by conorsch** [comment]
PR is up for #1876, so I'm branching from that and investigating these cleanup tasks in support of resolving #2222.

**Comment by conorsch** [comment]
The run-tests-as-root strategy seems to be motivated by site-wide packages settings for virtualenvs. If the tests are executed with normal user privileges in Travis, several required packages are not found, causing the tests to failed. The dependencies are visible when running with elevated privileges, however. 

The Ansible scripts install the pip packages globally, via elevated privileges. Even with that approach, the app tests can still be executed as a normal user inside the development VM. Not so in Travis. Started tinkering with less automagic in the Travis environment by setting `language: generic` and ripping out the Python-specific declarations, which resolved some problems, but not everything.

Given the disparity between the dev VM and Travis, I now suspect umask may be the culprit.

**Comment by conorsch** [comment]
Returning to Travis cleanup, now that #2221 is merged. Picking back up on the don't-run-tests-as-root fix:

> If the tests are executed with normal user privileges in Travis, several required packages are not found, causing the tests to fail.

Turns out the problem is PYTHONPATH disparities, and even root execution does not resolve. (I tested the umask and it's identical on local VMs and Travis.) Compare the following:

```
$ python -c 'import sys, pprint; pprint.pprint(sys.path)' # in Development VM
['',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
```
```
$ python -c 'import sys, pprint; pprint.pprint(sys.path)' # in Travis
['',
 '/opt/python/2.7.13/lib/python27.zip',
 '/opt/python/2.7.13/lib/python2.7',
 '/opt/python/2.7.13/lib/python2.7/plat-linux2',
 '/opt/python/2.7.13/lib/python2.7/lib-tk',
 '/opt/python/2.7.13/lib/python2.7/lib-old',
 '/opt/python/2.7.13/lib/python2.7/lib-dynload',
 '/opt/python/2.7.13/lib/python2.7/site-packages']
```

Note the conspicuous absence of `local/lib` in Travis. Might be worth pinning 2.7.6 in Travis, since that's what the Trusty is using. Specifically it's the `psutil` import in the pytest app test fixtures that throws the error:

```
The command "sudo sh -c "DISPLAY=:1 pytest -v securedrop/tests"" exited with 1.
1.10s$ DISPLAY=:1 pytest -v securedrop/tests/ ; cat tests/log/firefox.log
Traceback (most recent call last):
  File "/opt/python/2.7.13/lib/python2.7/site-packages/_pytest/config.py", line 367, in _importconftest
    mod = conftestpath.pyimport()
  File "/opt/python/2.7.13/lib/python2.7/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/opt/python/2.7.13/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/travis/build/conorsch/securedrop/securedrop/tests/conftest.py", line 7, in <module>
    import psutil
ImportError: No module named psutil
ERROR: could not load /home/travis/build/conorsch/securedrop/securedrop/tests/conftest.py
```

The above catches up with my notes from last time I worked on this. Will continue from there.

**Comment by conorsch** [comment]
Got most of the boxes checked in the original post, changes tracked in the `cleanup-travis-ci-config` branch.
