### ISSUE TITLE
transient travis failure: GNUPG ERROR key_generate

### ISSUE THREAD

**Issue by dachary** [freedomofpress/securedrop#2568]
Please use the appropriate part of the template: "Bug" or "Feature Request"

# Bug

## Description

<pre>
2017-11-11 11:45:56,443 GNUPG PROGRESS primegen X 100 100
2017-11-11 11:45:56,443 GNUPG GOOD_PASSPHRASE
2017-11-11 11:45:56,443 GNUPG ERROR key_generate 32849
2017-11-11 11:45:56,445 DEBUG DELETE http://127.0.0.1:46913/hub/session/f38d4921-a7d6-477d-88f2-0876968d8865 {"sessionId": "f38d4921-a7d6-477d-88f2-0876968d8865"}
Exception in thread Thread-2878:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_meta.py", line 650, in _read_response
    result._handle_status(keyword, value)
  File "/usr/local/lib/python2.7/dist-packages/gnupg/_parsers.py", line 993, in _handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: u'ERROR'
2017-11-11 11:45:56,447 DEBUG Finishing reading from stream "<open file '<fdopen>', mode 'rb' at 0x7f2f78d921e0>"...
2017-11-11 11:45:56,447 DEBUG Read    0 bytes total
2017-11-11 11:45:56,447 INFO Key created. Fingerprint: None
2017-11-11 11:45:56,455 DEBUG Finished Request
=============================== warnings summary ========
</pre>

## Steps to Reproduce

Unknown, this is a transient error.

## Expected Behavior

No error ;-)

## Actual Behavior

Very very rare failure.

## Comments

Wait for it to show up again and add a like to the travis logs for debugging:

* https://travis-ci.org/freedomofpress/securedrop/builds/300571913?utm_source=github_status&utm_medium=notification

**Comment by garrettr** [comment]
This is probably caused by the same underlying bug as #844 - race condition between python-gnupg and the test cleanup code.

**Comment by garrettr** [comment]
Note that the error is in `layout/test_source.py::TestSourceLayout::test_lookup[fr_FR] ERROR`, which is a functional test. This is a different way to arrive at the same type of race condition we had in #844. Since the functional tests create a standalone server, the test may initiate teardown while the standalone server is still using some resources (e.g. GPG KEYGEN was triggered as part of the test, and it can take a while, especially on a shared hosting platform such as Travis CI which typically has less available entropy than, say, a developer's workstation).

**Comment by dachary** [comment]
> same type of race condition we had in #844. 

#844 was because two independent processes created GPG keys. I don't believe this error could have the same cause but ... maybe I'm missing something ? Which process / threads could race against each other and create this problem ?

**Comment by dachary** [comment]
We did not see this error in the past few months, closing as cannot reproduce.
