### ISSUE TITLE
Source interface error

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#2634]
# Bug

## Description
Server side error while trying to view the source interview.

## Steps to Reproduce

Installed a stage instance from the 0.5 branch.

Commit: `f9a7b83f350a7682a6754091c390ae9cc76e4880`

After installation tried to open the onion address for the source interface.

## Expected Behavior

I am supposed to view the source interface.

## Actual Behavior

I am seeing a server error message.

```
Server error

Sorry, the website encountered an error and was unable to complete your request.

```
The log shows the following error.

```
[Wed Nov 29 20:37:49.475335 2017] [:info] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888] mod_wsgi (pid=1471, process='source', application='app-staging|'): Loading WSGI script '/var/www/source.wsgi'.
[Wed Nov 29 20:37:49.887998 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888] [2017-11-29 20:37:49,885] ERROR in app: Exception on / [GET]
[Wed Nov 29 20:37:49.888023 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888] Traceback (most recent call last):
[Wed Nov 29 20:37:49.888027 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Wed Nov 29 20:37:49.888031 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     response = self.full_dispatch_request()
[Wed Nov 29 20:37:49.888034 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Wed Nov 29 20:37:49.888038 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     rv = self.handle_user_exception(e)
[Wed Nov 29 20:37:49.888041 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Wed Nov 29 20:37:49.888044 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     reraise(exc_type, exc_value, tb)
[Wed Nov 29 20:37:49.888055 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Wed Nov 29 20:37:49.888059 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     rv = self.dispatch_request()
[Wed Nov 29 20:37:49.888062 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Wed Nov 29 20:37:49.888065 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Nov 29 20:37:49.888068 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/var/www/securedrop/source_app/main.py", line 27, in index
[Wed Nov 29 20:37:49.888071 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     return render_template('index.html')
[Wed Nov 29 20:37:49.888074 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 134, in render_template
[Wed Nov 29 20:37:49.888077 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     context, ctx.app)
[Wed Nov 29 20:37:49.888080 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 116, in _render
[Wed Nov 29 20:37:49.888084 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     rv = template.render(context)
[Wed Nov 29 20:37:49.888086 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 1008, in render
[Wed Nov 29 20:37:49.888090 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     return self.environment.handle_exception(exc_info, True)
[Wed Nov 29 20:37:49.888092 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
[Wed Nov 29 20:37:49.888095 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     reraise(exc_type, exc_value, tb)
[Wed Nov 29 20:37:49.888098 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/var/www/securedrop/source_templates/index.html", line 11, in top-level template code
[Wed Nov 29 20:37:49.888101 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     {% assets filters="jsmin", output="gen/source.js",
[Wed Nov 29 20:37:49.888105 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/ext/jinja2.py", line 186, in _render_assets
[Wed Nov 29 20:37:49.888108 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     urls = bundle.urls()
[Wed Nov 29 20:37:49.888111 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 806, in urls
[Wed Nov 29 20:37:49.888114 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     urls.extend(bundle._urls(new_ctx, extra_filters, *args, **kwargs))
[Wed Nov 29 20:37:49.888117 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 765, in _urls
[Wed Nov 29 20:37:49.888120 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     *args, **kwargs)
[Wed Nov 29 20:37:49.888123 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/bundle.py", line 609, in _build
[Wed Nov 29 20:37:49.888126 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     if ctx.updater else True
[Wed Nov 29 20:37:49.888129 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/updater.py", line 173, in needs_rebuild
[Wed Nov 29 20:37:49.888135 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     super(TimestampUpdater, self).needs_rebuild(bundle, ctx) or \\
[Wed Nov 29 20:37:49.888138 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/updater.py", line 103, in needs_rebuild
[Wed Nov 29 20:37:49.888141 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     return self.check_bundle_definition(bundle, ctx)
[Wed Nov 29 20:37:49.888145 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/updater.py", line 93, in check_bundle_definition
[Wed Nov 29 20:37:49.888149 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     cached_hash = ctx.cache.get(cache_key)
[Wed Nov 29 20:37:49.888151 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]   File "/usr/local/lib/python2.7/dist-packages/webassets/cache.py", line 185, in get
[Wed Nov 29 20:37:49.888154 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888]     f = open(filename, 'rb')
[Wed Nov 29 20:37:49.888158 2017] [:error] [pid 1471:tid 3255481067264] [remote 127.0.0.1:37888] IOError: [Errno 13] Permission denied: '/var/www/securedrop/static/.webassets-cache/7d262489daab354fc856a9250e4c560e'
```

**Comment by conorsch** [comment]
Trying to reproduce....

**Comment by redshiftzero** [comment]
I just freshly provisioned staging to try to reproduce this, but I'm able to access the source interface without issue:

<img width="966" alt="screen shot 2017-11-29 at 1 28 01 pm" src="https://user-images.githubusercontent.com/7832803/33399943-2ac0a200-d509-11e7-8415-85cbbb9823db.png">

**Comment by conorsch** [comment]
I used rc1 packages and also loading fine for me:

![source-interface-0 5-rc1-ok](https://user-images.githubusercontent.com/657862/33400264-55c23f76-d50a-11e7-86a1-a1e954d3e9fa.png)

So sounds like this is a workstation-specific problem. Happy to debug with you.

**Comment by redshiftzero** [comment]
The files on app in `/var/www/securedrop/static/.webassets-cache/` should be owned by the `www-data` user and group, is that the case for you @kushaldas?

**Comment by kushaldas** [comment]
@redshiftzero Yes.

```
# ls -l /var/www/securedrop/static/
total 20
drwxr-xr-x 2 www-data www-data 4096 Nov 29 18:26 css
drwxr-xr-x 2 www-data www-data 4096 Nov 29 18:26 fonts
drwxr-xr-x 2 www-data www-data 4096 Nov 29 19:37 gen
drwxr-xr-x 5 www-data www-data 4096 Nov 29 18:26 i
drwxr-xr-x 3 www-data www-data 4096 Nov 29 18:26 js
```

**Comment by kushaldas** [comment]
Found the cause. As i ran the application tests as root, the cache filed were owned by root. Closing the issue as removing those make everything fine.
