### ISSUE TITLE
OS X developer guide does not work

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#2698]
# Bug

## Description

Running through the OS X developer guide throws a stacktrace and doesn't actually work on a fresh, new computer.

## Steps to Reproduce

In a new OS X machine run the `pip install -U virtualenvwrapper` described [here](https://raw.githubusercontent.com/freedomofpress/securedrop/develop/docs/development/setup_development.rst).

## Expected Behavior

Following the developer guide should let a new developer get their dev environment working.

## Actual Behavior

See below stacktrace
```
Installing collected packages: virtualenv, pbr, six, stevedore, virtualenv-clone, virtualenvwrapper
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/virtualenv.pyc'
```

**Comment by freddymartinez9** [comment]
I believe the docs have to read `sudo -H pip install -U virtualenvwrapper --ignore-installed six`.

**Comment by conorsch** [comment]
Docs referred to here: https://docs.securedrop.org/en/stable/development/getting_started.html#mac-os-x

I don't have a Mac to try to reproduce. It's always puzzled me that the `pip` commands to install virtualenvwrapper didn't require admin rights. On Linux, I typically use `pip install --user <package>` to install pip packages without admin privileges, but in our Linux docs we recommend virtualenvwrapper from the distro repositories. 

Perhaps there's a homebrew workflow that would permit normal user privileges for pulling in pip, rather than `sudo easy_install pip`?

**Comment by lislis** [comment]
I ran into the same issue and @freddymartinez9 command fixed it for me. After that installation runs smoothly

**Comment by freddymartinez9** [comment]
@lislis thank you for testing! Opened a PR for our documentation.
