### ISSUE TITLE
500 internal server error when updating logo via Journalist interface

### ISSUE THREAD

**Issue by emkll** [freedomofpress/securedrop#2835]
# Bug

## Description

When updating a logo through the Instance Config functionality of the Admin interface, an internal server error occurs.
 
## Steps to Reproduce

1. Navigate to Journalist Interface
2. Click on Admin
3. Click on Instance Config
4. Click browse and upload an image file
5. Click on Update Logo

## Expected Behavior
The logo is updated

## Actual Behavior

An error 500 occurs:
```
[Thu Jan 11 14:34:49.978865 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217] [2018-01-11 14:34:49,973] ERROR in app: Exception on /admin/config [POST]
[Thu Jan 11 14:34:49.978893 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217] Traceback (most recent call last):
[Thu Jan 11 14:34:49.978899 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
[Thu Jan 11 14:34:49.978904 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     response = self.full_dispatch_request()
[Thu Jan 11 14:34:49.978910 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
[Thu Jan 11 14:34:49.978914 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     rv = self.handle_user_exception(e)
[Thu Jan 11 14:34:49.978919 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
[Thu Jan 11 14:34:49.978924 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     reraise(exc_type, exc_value, tb)
[Thu Jan 11 14:34:49.978928 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
[Thu Jan 11 14:34:49.978933 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     rv = self.dispatch_request()
[Thu Jan 11 14:34:49.978937 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
[Thu Jan 11 14:34:49.978942 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     return self.view_functions[rule.endpoint](**req.view_args)
[Thu Jan 11 14:34:49.978947 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/var/www/securedrop/journalist_app/decorators.py", line 14, in wrapper
[Thu Jan 11 14:34:49.978958 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     return func(*args, **kwargs)
[Thu Jan 11 14:34:49.978962 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/var/www/securedrop/journalist_app/admin.py", line 36, in manage_config
[Thu Jan 11 14:34:49.978967 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     f.save(static_filepath)
[Thu Jan 11 14:34:49.978971 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]   File "/usr/local/lib/python2.7/dist-packages/werkzeug/datastructures.py", line 2703, in save
[Thu Jan 11 14:34:49.978976 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217]     dst = open(dst, 'wb')
[Thu Jan 11 14:34:49.978980 2018] [:error] [pid 1433:tid 3501914679040] [remote 127.0.0.1:58217] IOError: [Errno 13] Permission denied: '/var/www/securedrop/static/i/logo.png'
```

## Comments

Related to https://github.com/freedomofpress/securedrop/issues/2827
It appears to be an AppArmor profile

**Comment by redshiftzero** [comment]
Closed via #2836
