### ISSUE TITLE
`make lint` doesn't "just work"

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#2911]
# Bug

## Description

I can't run `make lint` on `develop` in either vagrant or my host.

## Steps to Reproduce

`make lint` on `develop`

## Expected Behavior

Things are linted, and the command exits 0 unless there is a lint error.

## Actual Behavior

```
cd securedrop && make lint
make[1]: Entering directory `/vagrant/securedrop'
find . -name '*.py' | xargs pylint --reports=no --errors-only --disable=import-error
Using config file /vagrant/securedrop/pylintrc
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python2.7/dist-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1315, in __init__
    linter.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 678, in load_config_file
    self.global_set_option(option, value)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 576, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 768, in set_option
    value = _validate(value, optdict, optname)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 233, in _validate
    return _call_validator(_type, optdict, name, value)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 214, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 204, in <lambda>
    'choice': lambda opt, name, value: _choice_validator(opt['choices'], name, value),
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 161, in _choice_validator
    raise optparse.OptionValueError(msg % (name, value, choices))
optparse.OptionValueError: option spelling-dict: invalid value: u'en_US', should be in ['']
```

## Comments

If there is something special like sourcing a `venv/bin/activate`, that should be in the script.

**Comment by heartsucker** [comment]
Ok, so maybe it does work but I got docker images out of sync across branches which means we have implicit dependencies between `ci-lint` and `ci-lint-image` which means that the Makefile should rebuild the latter before running the former.

Or.

We use `git ls-tree -r HEAD --name-only | xargs cat | sha256sum | awk '{ print $1 }'` as the docker tag so we can cache it, and then check the cache to speed up the build.

```
heartsucker@pythagoras:~/code/freedomofpress/securedrop (develop)$ time git ls-tree -r HEAD --name-only | xargs cat | sha256sum
15aef4ff89b578cb8400f5bdd7c442bf1dc319666cd907eaa08fa431f09ecf0c  -

real	0m0.147s
user	0m0.144s
sys	0m0.012s
```

**Comment by heartsucker** [comment]
The reason we shouldn't use the `git rev-parse HEAD` as the tag is that when files change under that tag (during normal development), we don't get an error that the container needs to be rebuilt.

**Comment by heartsucker** [comment]
The downside is that we end up tagging A SHIT LOAD of images which means people will have to frequently prune their system.
