### ISSUE TITLE
securedrop-admin setup script fails with confusing errors

### ISSUE THREAD

**Issue by b-meson** [freedomofpress/securedrop#3199]
# Bug

## Description

We previously had a virtualenv in `~/Persistence/securedrop/.venv` that had the packages needed to admin SecureDrop. In 0.6 we moved the location to `~/Persistence/securedrop/admin/.venv`. Right now, if you delete the _old_ path and run `./securedrop-admin setup -v`, the script errors out with an error. 

## Steps to Reproduce

Note: I was on a 0.5.2 release before I checked out the 0.6 code.

I removed the old virtualenv in `~/Persistence/securedrop/.venv` and attempted to run `./securedrop-admin -v setup`. I got the following output:

```
please run './securedrop-admin setup' first
```
So then I upgraded to 0.6 by doing a `git checkout` to the 0.6 tag. 

I reran `./securedrop-admin -v setup` and got the following stack trace:

```
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin -v setup 
INFO: Virtualenv already exists, not creating
INFO: Checking Python dependencies for securedrop-admin
DEBUG: ERROR: /home/amnesia/Persistent/securedrop/admin/.venv/bin/pip cannot be found.

ERROR: Failed to install pip dependencies. Check network connection and try again.
Traceback (most recent call last):
  File "./admin/bootstrap.py", line 213, in <module>
    args.func(args)
  File "./admin/bootstrap.py", line 149, in envsetup
    install_pip_dependencies(args)
  File "./admin/bootstrap.py", line 186, in install_pip_dependencies
    stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['torify', '/home/amnesia/Persistent/securedrop/admin/.venv/bin/pip', 'install', '-r', '/home/amnesia/Persistent/securedrop/admin/requirements.txt', '--require-hashes', '-U', '--upgrade-strategy', 'only-if-needed']' returned non-zero exit status 1
```

Curiously, I again ran `./securedrop-admin setup` and got another error
```
INFO: Virtualenv already exists, not creating
INFO: Check Python dependencies for securedrop-admin
ERROR: failed to install pip dependencies. Check network connections and try again
````

It should be pointed out that networking is not the issue as I am fully connected to Tor browser and can access the web. Running a `rm -rf ~/Persistence/securedrop/admin/.venv/` and rerunning the setup script resolved the issue for me.
 
## Expected Behavior

The setup script should complete without issue. If it does fail, the output should be indicative of a the actual error.

## Comments

Suggestions to fix, any other relevant information.

**Comment by b-meson** [comment]
I clumsily opened two issues but #3200 should have more details. Closing as duplicate.
