### ISSUE TITLE
`make update-pip-requirements` fails

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3292]
# Bug

## Description

Running `make update-pip-requirements` from the root directory fails.

## Steps to Reproduce

```
$ make update-pip-requirements 
make -C admin update-pip-requirements
make[1]: Entering directory '/home/heartsucker/code/freedomofpress/securedrop/admin'
bin/dev-shell pip-compile --generate-hashes --output-file requirements.txt requirements.in requirements-ansible.in
Run with DOCKER_BUILD_VERBOSE=true for more information
Docker image build in progress  done !
Traceback (most recent call last):
  File "/opt/.venv/bin/pip-compile", line 7, in <module>
    from piptools.scripts.compile import cli
  File "/opt/.venv/local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from pip.req import InstallRequirement, parse_requirements
ImportError: No module named req
Makefile:9: recipe for target 'update-pip-requirements' failed
make[1]: *** [update-pip-requirements] Error 1
make[1]: Leaving directory '/home/heartsucker/code/freedomofpress/securedrop/admin'
Makefile:127: recipe for target 'update-pip-requirements' failed
make: *** [update-pip-requirements] Error 2
```

## Expected Behavior

The command updates the requirements.

## Actual Behavior

It breaks.

**Comment by redshiftzero** [comment]
This is happening on `make -C admin update-pip-requirements` because of a change made in pip 10 to move `pip.req` to `pip._internal.req`, which is why we're getting this `ImportError` in the traceback in the issue description. Updating to a more recent version of pip-tools [should resolve](https://github.com/jazzband/pip-tools/issues/656) this issue.
