### ISSUE TITLE
Replace QR code SVG with PNG

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3293]
# Feature request

## Description

When Tor Browser is using the recommended security settings, SVGs are blocked. We need to display on-demand images for QR codes.

Related #3291.

## User Stories

As an admin, I don't want to be confused about why my QR code isn't rendering.

As an admin, I don't have the security knowledge to figure out when I can or cannot use lower Tor Browser security settings.

**Comment by heartsucker** [comment]
```
Downloading/unpacking qrcode[pil]==6.0 (from -r requirements/securedrop-app-code-requirements.txt (line 25))
  Downloading qrcode-6.0-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2517, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2514, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/_markerlib/markers.py", line 113, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'platform_system' is not defined
```

This is already annoying to fix.

**Comment by legoktm** [comment]
> NameError: name 'platform_system' is not defined

You'll need pip >= 8.1.2 for that to work.

**Comment by redshiftzero** [comment]
This is lower priority since the Tor Browser Security Slider set to Safest isn't the recommended security setting for the Journalist/Admin Interface (relevant: #1476), but this is a nice to have.

**Comment by legoktm** [comment]
We already render a plain-text ASCII QR code via `manage.py`, I wonder if we could just render that with a monospace font in HTML.
