### ISSUE TITLE
make update-pip-requirements fails on develop

### ISSUE THREAD

**Issue by heartsucker** [freedomofpress/securedrop#3634]
## Description

Like the title says. We can't run the `make` script.

## Steps to Reproduce

```
make update-pip-requirements
```

## Expected Behavior

Script exists 0

## Actual Behavior

```
...
make[1]: Leaving directory '/home/heartsucker/code/freedomofpress/securedrop/admin'
pip-compile --output-file securedrop/requirements/develop-requirements.txt \
	admin/requirements-ansible.in \
	securedrop/requirements/develop-requirements.in
Traceback (most recent call last):
  File "/home/heartsucker/.local/bin/pip-compile", line 7, in <module>
    from piptools.scripts.compile import cli
  File "/home/heartsucker/.local/lib/python2.7/site-packages/piptools/scripts/compile.py", line 11, in <module>
    from pip.req import InstallRequirement, parse_requirements
ImportError: No module named req
Makefile:127: recipe for target 'update-pip-requirements' failed
make: *** [update-pip-requirements] Error 1
```

**Comment by heartsucker** [comment]
This could be my environment only, but like honestly with python i'm still like "who knows" sometimes.

**Comment by heartsucker** [comment]
Wait. Yep, this is definitely a me problem. We run some `pip-compile` commands in containers and some not in containers. This one is not... *sigh* dammit pip, why you doing this to me?
