### ISSUE TITLE
Update documentation on how to run config tests

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#3780]
## Description

We need to update the documentation on the config tests as it is no longer accurate (the root-level testinfra directory is gone entirely as of #3703):

https://docs.securedrop.org/en/latest/development/testing_configuration_tests.html

**Comment by conorsch** [comment]
Related to #3208. IMO, those two should be handled together. Happy to update the docs as part of the next sprint.

**Comment by redshiftzero** [comment]
Reading through #3208, it sounds like those are more extensive changes, so unless the deprecation of the _entire_ Vagrantfile is imminent, we should keep the tickets separate

**Comment by zenmonkeykstop** [comment]
I tried running the tests by doing

```
make build-debs
molecule test -s libvirt-staging
```

And it bombed out with the errors below. Is there something else that needs doing?
```
--> Scenario: 'libvirt-staging'
--> Action: 'verify'
--> Executing Testinfra tests found in /home/kstop/projects/securedrop/securedrop-kog/molecule/libvirt-staging/../testinfra/staging//...
Traceback (most recent call last):
  File "/home/kstop/.virtualenvs/securedrop/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 943, in pytest_cmdline_parse
    self.parse(args)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 1108, in parse
    self._preparse(args, addopts=addopts)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 1079, in _preparse
    args=args, parser=self._parser)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 989, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 311, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 317, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 331, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 378, in _importconftest
    self.consider_conftest(mod)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 401, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/_pytest/config.py", line 250, in register
    ret = super(PytestPluginManager, self).register(plugin, name)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 254, in register
    hook._maybe_apply_history(hookimpl)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 650, in _maybe_apply_history
    res = self._hookexec(self, [method], kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
    _reraise(*ex)  # noqa
  File "/home/kstop/.virtualenvs/securedrop/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/kstop/projects/securedrop/securedrop-kog/molecule/testinfra/staging/conftest.py", line 91, in pytest_namespace
    return securedrop_import_testinfra_vars(target_host, with_header=True)
  File "/home/kstop/projects/securedrop/securedrop-kog/molecule/testinfra/staging/conftest.py", line 35, in securedrop_import_testinfra_vars
    export_ci_var_overrides()
  File "/home/kstop/projects/securedrop/securedrop-kog/molecule/testinfra/staging/conftest.py", line 48, in export_ci_var_overrides
    app_ip = lookup_aws_private_address(molecule_info, 'app-staging')
  File "/home/kstop/projects/securedrop/securedrop-kog/molecule/testinfra/staging/conftest.py", line 74, in lookup_aws_private_address
    host_ip = host_info['priv_address']
KeyError: 'priv_address'
An error occured during the test sequence.  Cleaning up.
```
