### ISSUE TITLE
error on alembic upgrade head --sql

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop#4417]
## Description

When creating a database migration and following [these steps](https://docs.securedrop.org/en/release-0.12.2/development/database_migrations.html#creating-migration), you'll reach the `alembic upgrade head --sql` check which will fail, see below:

```
Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 486, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 480, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python2.7/dist-packages/alembic/config.py", line 463, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/usr/local/lib/python2.7/dist-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/dist-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python2.7/dist-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "alembic/env.py", line 80, in <module>
    run_migrations_offline()
  File "alembic/env.py", line 53, in run_migrations_offline
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/home/creviera/workspace/freedomofpress/securedrop/securedrop/alembic/versions/3d91d6948753_create_source_uuid_column.py", line 30, in upgrade
    sources = conn.execute(sa.text("SELECT * FROM sources_tmp")).fetchall()
AttributeError: 'NoneType' object has no attribute 'fetchall'
```

## Steps to Reproduce

From `develop` branch...

```
cd securedrop/
./bin/dev-shell
source bin/dev-deps
maybe_create_config_py
alembic upgrade head --sql
```

## Comments

For now, we can just ignore this error when creating a migration and make sure to have good unit tests (follow https://docs.securedrop.org/en/release-0.12.2/development/database_migrations.html#unit-testing-migrations).

**Comment by heartsucker** [comment]
I think this can be closed as "not a bug" since using `--sql` with a `SELECT` statement isn't supported by `alembic`. See docs: https://alembic.sqlalchemy.org/en/latest/offline.html?highlight=sql#writing-migration-scripts-to-support-script-generation

**Comment by heartsucker** [comment]
Lol whoops wait the docs we wrote *do* say to use `--sql` to dump it to `stdout`. The bug is that the docs are wrong, not the code. Maybe we should change the title to reflect that?
