### ISSUE TITLE
make lint target fails locally

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop#4423]
## Description

The linting target fails locally

## Steps to Reproduce

`make lint`

## Expected Behavior

lint target passes

## Actual Behavior

```
[...]
find . -name '*.py' | xargs pylint --reports=no --errors-only \
	   --disable=import-error \
	   --disable=no-name-in-module \
	   --disable=unexpected-keyword-arg \
	   --disable=too-many-function-args \
	   --disable=import-error \
	   --max-line-length=100
Using config file /Users/redshiftzero/Documents/Github/securedrop-functional-test/securedrop/securedrop/pylintrc
Traceback (most recent call last):
  File "/Users/redshiftzero/.virtualenvs/securedrop/bin/pylint", line 11, in <module>
    sys.exit(run_pylint())
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/lint.py", line 1315, in __init__
    linter.load_config_file()
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 678, in load_config_file
    self.global_set_option(option, value)
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 576, in global_set_option
    self._all_options[opt].set_option(opt, value)
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 768, in set_option
    value = _validate(value, optdict, optname)
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 233, in _validate
    return _call_validator(_type, optdict, name, value)
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 214, in _call_validator
    return VALIDATORS[opttype](optdict, option, value)
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 204, in <lambda>
    'choice': lambda opt, name, value: _choice_validator(opt['choices'], name, value),
  File "/Users/redshiftzero/.virtualenvs/securedrop/lib/python2.7/site-packages/pylint/config.py", line 161, in _choice_validator
    raise optparse.OptionValueError(msg % (name, value, choices))
optparse.OptionValueError: option spelling-dict: invalid value: u'en_US', should be in ['']
make[1]: *** [lint] Error 1
make: *** [app-lint] Error 2
```

**Comment by redshiftzero** [comment]
This is happening for linux also apparently
