### ISSUE TITLE
CI: network flake during linting job

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#4707]
Lint test flake on a `docs-` branch, filing in case there's anything we can do on our end to increase resiliency:

https://circleci.com/gh/freedomofpress/securedrop/32661

```
...
    100% |████████████████████████████████| 61kB 8.4MB/s 
Collecting pytest-xdist==1.18.2 (from -r requirements/python3/develop-requirements.txt (line 84))
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:
...
```

**Comment by eloquence** [comment]
Another one, from nightly static analysis:
https://circleci.com/gh/freedomofpress/securedrop/35252#build-timing

**Comment by eloquence** [comment]
Possibly related "Connection reset by peer" flake in linting job:
https://circleci.com/gh/freedomofpress/securedrop/35377#build-timing

**Comment by deeplow** [comment]
> [](https://circleci.com/gh/freedomofpress/securedrop/32661)
> 
> ```
> ...
>     100% |████████████████████████████████| 61kB 8.4MB/s 
> Collecting pytest-xdist==1.18.2 (from -r requirements/python3/develop-requirements.txt (line 84))
> Exception:
> Traceback (most recent call last):
>   File "/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 377, in _make_request
>     httplib_response = conn.getresponse(buffering=True)
> TypeError: getresponse() got an unexpected keyword argument 'buffering'
> 
> During handling of the above exception, another exception occurred:
> ...
> ```

I had this same issue when doing `make build-debs`:

```
    TASK [build-securedrop-app-code-deb-pkg : Install SecureDrop Python requirements in container] ***
    fatal: [xenial-sd-app]: FAILED! => {"changed": true, "cmd": "pip3 install --no-binary :all: --require-hashes -r /tmp/securedrop-app-code_1.1.0~rc1+xenial_amd64-prep/requirements.txt", "delta": "0:00:44.748849", "end": "2019-10-19 14:55:40.858817", "msg": "non-zero return code", "rc": 2, "start": "2019-10-19 14:54:56.109968", "stderr": "Exception:\nTraceback (most recent call last):\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 377, in _make_request\n    httplib_response = conn.getresponse(buffering=True)\nTypeError: getresponse() got an unexpected keyword argument 'buffering'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 379, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.5/http/client.py\", line 1213, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.5/http/client.py\", line 307, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.5/http/client.py\", line 268, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\n  File \"/usr/lib/python3.5/ssl.py\", line 929, in recv_into\n    return self.read(nbytes, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 791, in read\n    return self._sslobj.read(len, buffer)\n  File \"/usr/lib/python3.5/ssl.py\", line 575, in read\n    v = self._sslobj.read(len, buffer)\nsocket.timeout: The read operation timed out\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 560, in urlopen\n    body=body, headers=headers)\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 381, in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 309, in _raise_timeout\n    raise ReadTimeoutError(self, url, \"Read timed out. (read timeout=%s)\" % timeout_value)\nrequests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3/dist-packages/pip/basecommand.py\", line 209, in main\n    status = self.run(options, args)\n  File \"/usr/lib/python3/dist-packages/pip/commands/install.py\", line 328, in run\n    wb.build(autobuilding=True)\n  File \"/usr/lib/python3/dist-packages/pip/wheel.py\", line 748, in build\n    self.requirement_set.prepare_files(self.finder)\n  File \"/usr/lib/python3/dist-packages/pip/req/req_set.py\", line 360, in prepare_files\n    ignore_dependencies=self.ignore_dependencies))\n  File \"/usr/lib/python3/dist-packages/pip/req/req_set.py\", line 512, in _prepare_file\n    finder, self.upgrade, require_hashes)\n  File \"/usr/lib/python3/dist-packages/pip/req/req_install.py\", line 273, in populate_link\n    self.link = finder.find_requirement(self, upgrade)\n  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 442, in find_requirement\n    all_candidates = self.find_all_candidates(req.name)\n  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 400, in find_all_candidates\n    for page in self._get_pages(url_locations, project_name):\n  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 545, in _get_pages\n    page = self._get_page(location)\n  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 648, in _get_page\n    return HTMLPage.get_page(link, session=self.session)\n  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 757, in get_page\n    \"Cache-Control\": \"max-age=600\",\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 480, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/lib/python3/dist-packages/pip/download.py\", line 378, in request\n    return super(PipSession, self).request(method, url, *args, **kwargs)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 468, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 576, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py\", line 46, in send\n    resp = super(CacheControlAdapter, self).send(request, **kw)\n  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py\", line 376, in send\n    timeout=timeout\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 610, in urlopen\n    _stacktrace=sys.exc_info()[2])\n  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py\", line 228, in increment\n    total -= 1\nTypeError: unsupported operand type(s) for -=: 'Retry' and 'int'\nYou are using pip version 8.1.1, however version 19.3.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.", "stderr_lines": ["Exception:", "Traceback (most recent call last):", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 377, in _make_request", "    httplib_response = conn.getresponse(buffering=True)", "TypeError: getresponse() got an unexpected keyword argument 'buffering'", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 379, in _make_request", "    httplib_response = conn.getresponse()", "  File \"/usr/lib/python3.5/http/client.py\", line 1213, in getresponse", "    response.begin()", "  File \"/usr/lib/python3.5/http/client.py\", line 307, in begin", "    version, status, reason = self._read_status()", "  File \"/usr/lib/python3.5/http/client.py\", line 268, in _read_status", "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")", "  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto", "    return self._sock.recv_into(b)", "  File \"/usr/lib/python3.5/ssl.py\", line 929, in recv_into", "    return self.read(nbytes, buffer)", "  File \"/usr/lib/python3.5/ssl.py\", line 791, in read", "    return self._sslobj.read(len, buffer)", "  File \"/usr/lib/python3.5/ssl.py\", line 575, in read", "    v = self._sslobj.read(len, buffer)", "socket.timeout: The read operation timed out", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 560, in urlopen", "    body=body, headers=headers)", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 381, in _make_request", "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 309, in _raise_timeout", "    raise ReadTimeoutError(self, url, \"Read timed out. (read timeout=%s)\" % timeout_value)", "requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)", "", "During handling of the above exception, another exception occurred:", "", "Traceback (most recent call last):", "  File \"/usr/lib/python3/dist-packages/pip/basecommand.py\", line 209, in main", "    status = self.run(options, args)", "  File \"/usr/lib/python3/dist-packages/pip/commands/install.py\", line 328, in run", "    wb.build(autobuilding=True)", "  File \"/usr/lib/python3/dist-packages/pip/wheel.py\", line 748, in build", "    self.requirement_set.prepare_files(self.finder)", "  File \"/usr/lib/python3/dist-packages/pip/req/req_set.py\", line 360, in prepare_files", "    ignore_dependencies=self.ignore_dependencies))", "  File \"/usr/lib/python3/dist-packages/pip/req/req_set.py\", line 512, in _prepare_file", "    finder, self.upgrade, require_hashes)", "  File \"/usr/lib/python3/dist-packages/pip/req/req_install.py\", line 273, in populate_link", "    self.link = finder.find_requirement(self, upgrade)", "  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 442, in find_requirement", "    all_candidates = self.find_all_candidates(req.name)", "  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 400, in find_all_candidates", "    for page in self._get_pages(url_locations, project_name):", "  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 545, in _get_pages", "    page = self._get_page(location)", "  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 648, in _get_page", "    return HTMLPage.get_page(link, session=self.session)", "  File \"/usr/lib/python3/dist-packages/pip/index.py\", line 757, in get_page", "    \"Cache-Control\": \"max-age=600\",", "  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 480, in get", "    return self.request('GET', url, **kwargs)", "  File \"/usr/lib/python3/dist-packages/pip/download.py\", line 378, in request", "    return super(PipSession, self).request(method, url, *args, **kwargs)", "  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 468, in request", "    resp = self.send(prep, **send_kwargs)", "  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/sessions.py\", line 576, in send", "    r = adapter.send(request, **kwargs)", "  File \"/usr/share/python-wheels/CacheControl-0.11.5-py2.py3-none-any.whl/cachecontrol/adapter.py\", line 46, in send", "    resp = super(CacheControlAdapter, self).send(request, **kw)", "  File \"/usr/share/python-wheels/requests-2.9.1-py2.py3-none-any.whl/requests/adapters.py\", line 376, in send", "    timeout=timeout", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/connectionpool.py\", line 610, in urlopen", "    _stacktrace=sys.exc_info()[2])", "  File \"/usr/share/python-wheels/urllib3-1.13.1-py2.py3-none-any.whl/urllib3/util/retry.py\", line 228, in increment", "    total -= 1", "TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'", "You are using pip version 8.1.1, however version 19.3.1 is available.", "You should consider upgrading via the 'pip install --upgrade pip' command."], "stdout": "Collecting alembic==0.9.9 (from -r /tmp/securedrop-app-code_1.1.0~rc1+xenial_amd64-prep/requirements.txt (line 7))\n  Downloading https://files.pythonhosted.org/packages/89/03/756d5b8e1c90bf283c3f435766aa3f20208d1c3887579dd8f2122e01d5f4/alembic-0.9.9.tar.gz (1.0MB)\nCollecting argon2-cffi==18.1.0 (from -r /tmp/securedrop-app-code_1.1.0~rc1+xenial_amd64-prep/requirements.txt (line 9))", "stdout_lines": ["Collecting alembic==0.9.9 (from -r /tmp/securedrop-app-code_1.1.0~rc1+xenial_amd64-prep/requirements.txt (line 7))", "  Downloading https://files.pythonhosted.org/packages/89/03/756d5b8e1c90bf283c3f435766aa3f20208d1c3887579dd8f2122e01d5f4/alembic-0.9.9.tar.gz (1.0MB)", "Collecting argon2-cffi==18.1.0 (from -r /tmp/securedrop-app-code_1.1.0~rc1+xenial_amd64-prep/requirements.txt (line 9))"]}
```
But I was able to fix it by removing the virtualenv and recreating according to the docs `https://docs.securedrop.org/en/latest/development/setup_development.html#id1`

**Note:** I had used `make build-debs` success fully in the past

**Comment by eloquence** [comment]
Haven't seen this in a while and docs have recently migrated; we can reopen if we observe again.
