### ISSUE TITLE
Error while unpacking setuptools from distribute

### ISSUE THREAD

**Issue by runasand** [freedomofpress/securedrop#491]
While installing *securedrop-app*, I noticed the below error fly past. I am not sure what this means for the installation of SecureDrop.

```
Downloading/unpacking setuptools>=0.7 (from distribute)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pip.index.py", line 243, in _get_queued_page
    for link in page.rel_links():
  File "/usr/lib/python2.7/dist-packages/pip.index.py", line 525, in rel_links
    for url in self.scraped_rel_links():
  File "/usr/lib/python2.7/dist-packages/pip.index.py", line 542, in scraped_rel_links
    url = match.group(1) or match.group(2) or match.group(3)
IndexError: no such group
```

**Comment by garrettr** [comment]
We are now using pip 1.5.4 as of SecureDrop 0.3. I also haven't seen this error message in a long time, so I think it is resolved in the manner suggested by @diracdeltas.
