### ISSUE TITLE
Python errors in output from  ./securedrop-admin restore

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5029]
## Description

Running in Tails 3.16, when the `./securedrop-admin restore` command is run for the first time, the output  includes the error messages below.

## Steps to Reproduce

(Tails 3.16, fresh Prod VM or HW instance)
- on the Admin Workstation back up the instance using `./securedrop-admin backup`
- restore the instance using `./securedrop-admin restore <backupFileName>`

## Expected Behavior
Command output includes no errors.

## Actual Behavior
Command output looks like:
<details><summary>click to open</summary>

```
amnesia@amnesia:~/Persistent/securedrop$ ./securedrop-admin restore sd-backup-2019-11-25--20-14-51.tar.gz 
INFO: Restoring the SecureDrop Application Server from backup

PLAY [Restore SecureDrop Application Server from previous config.] *************************

TASK [Gathering Facts] *********************************************************************
ok: [app]

TASK [restore : Create temporary directory for Tor configuration check] ********************
changed: [app]

TASK [restore : Fetch current Tor configuration from app server] ***************************
changed: [app]

TASK [restore : Create directory to hold the Tor configuration from the backup] ************
changed: [app]

TASK [restore : Extract Tor configuration from backup] *************************************
changed: [app]

TASK [restore : Check for Tor configuration differences between the backup and server] *****
changed: [app]

TASK [restore : Remove temporary directory for Tor configuration check] ********************
changed: [app]

TASK [restore : Copy backup to application server] *****************************************
changed: [app]

TASK [restore : Extract backup] ************************************************************
changed: [app]

TASK [restore : Reconfigure securedrop-app-code] *******************************************
changed: [app]

TASK [restore : Reconfigure securedrop-config] *********************************************
changed: [app]

TASK [restore : Reload Apache service] *****************************************************
changed: [app]

TASK [restore : Reload Tor service] ********************************************************
changed: [app]

TASK [restore : Wait for Tor reload] *******************************************************
changed: [app]

PLAY RECAP *********************************************************************************
app                        : ok=14   changed=13   unreachable=0    failed=0   

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa7ea4c7a60>
Traceback (most recent call last):
  File "/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```
</details>

Please provide screenshots where appropriate.

## Comments
These errors don't appear to affect the restore script itself -  the restore succeeds as far as I can tell. Subsequent restore commands do not display the errors.

**Comment by zenmonkeykstop** [comment]
Note that this is Tails 3.16 - if these errors were reported on a production system, first advice would be to upgrade to 4.0...

**Comment by redshiftzero** [comment]
I confirm this is not happening on Tails 4

**Comment by conorsch** [comment]
Have seen this, as well, but never under Tails 4. See upstream tickets:

* https://github.com/ansible/ansible/issues/21982
* https://github.com/ansible/ansible/issues/32095

In sum, recommending upgrade is definitely the right response here.

**Comment by eloquence** [comment]
Should we close this, given that we no longer support the Tails 3 series?

**Comment by redshiftzero** [comment]
yep lets close
