### ISSUE TITLE
Vagrant error due to problem in Ruby code

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5093]
## Description

`make upgrade-start` failed twice with the following error.

```
    failed: [localhost] (item={'name': 'app-staging', 'box': 'fpf/securedrop-app-xenial', 'box_url': '../vagrant-packager/box_files/app_xenial_metadata.json', 'instance_raw_config_args': ['ssh.insert_key = false'], 'provider_override_args': ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'memory': 1024, 'private_ip': '10.0.1.2', 'groups': ['securedrop_application_server', 'securedrop', 'staging']}) => {"changed": false, "item": {"box": "fpf/securedrop-app-xenial", "box_url": "../vagrant-packager/box_files/app_xenial_metadata.json", "groups": ["securedrop_application_server", "securedrop", "staging"], "instance_raw_config_args": ["ssh.insert_key = false"], "memory": 1024, "name": "app-staging", "private_ip": "10.0.1.2", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "msg": "ERROR: See log file '/tmp/molecule/securedrop/upgrade/vagrant-app-staging.err'"}

        failed: [localhost] (item={'name': 'mon-staging', 'box': 'fpf/securedrop-mon-xenial', 'box_url': '../vagrant-packager/box_files/mon_xenial_metadata.json', 'instance_raw_config_args': ['ssh.insert_key = false'], 'provider_override_args': ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'memory': 1024, 'private_ip': '10.0.1.3', 'groups': ['securedrop_monitor_server', 'securedrop', 'staging']}) => {"changed": false, "item": {"box": "fpf/securedrop-mon-xenial", "box_url": "../vagrant-packager/box_files/mon_xenial_metadata.json", "groups": ["securedrop_monitor_server", "securedrop", "staging"], "instance_raw_config_args": ["ssh.insert_key = false"], "memory": 1024, "name": "mon-staging", "private_ip": "10.0.1.3", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "msg": "ERROR: See log file '/tmp/molecule/securedrop/upgrade/vagrant-mon-staging.err'"}

        failed: [localhost] (item={'name': 'apt', 'box': 'bento/ubuntu-16.04', 'provider_override_args': ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"], 'memory': 256, 'groups': ['aptservers']}) => {"changed": false, "item": {"box": "bento/ubuntu-16.04", "groups": ["aptservers"], "memory": 256, "name": "apt", "provider_override_args": ["vm.synced_folder './', '/vagrant', disabled: true, type: 'nfs'"]}, "msg": "ERROR: See log file '/tmp/molecule/securedrop/upgrade/vagrant-apt.err'"


    RUBY CODE ERROR


    /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:87:in `new': Initialization parameters must be an attributes hash, got NilCla

    ss nil (ArgumentError)

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `block in load'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `each'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:77:in `load'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-libvirt-0.6.0/lib/fog/libvirt/models/compute/volumes.rb:11:in `all'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-libvirt-0.6.0/lib/fog/libvirt/models/compute/server.rb:138:in `block in volumes'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-libvirt-0.6.0/lib/fog/libvirt/models/compute/server.rb:138:in `map'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-libvirt-0.6.0/lib/fog/libvirt/models/compute/server.rb:138:in `volumes'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:78:in `block in object_attributes'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:77:in `map'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:77:in `object_attributes'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:63:in `attribute_string'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:53:in `object_string'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:14:in `block in format'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/formatador-0.2.5/lib/formatador.rb:92:in `indent'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:41:in `indent'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/formatador.rb:14:in `format'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/model.rb:24:in `inspect'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:19:in `inspect'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/fog-core-1.43.0/lib/fog/core/collection.rb:19:in `to_s'

            from /home/kdas/.vagrant.d/gems/2.4.9/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:17:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'

            from /opt/vagrant/embedded/gems/2.2.6/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
```

## Steps to Reproduce

No proper reproducer yet

## Expected Behavior

The command should finish normally

## Actual Behavior

Look at the error message above.

**Comment by legoktm** [comment]
Closing since the vagrant staging environment was removed.
