### ISSUE TITLE
CI failing due to setuptools change

### ISSUE THREAD

**Issue by zenmonkeykstop** [freedomofpress/securedrop#5150]
## Description

The `staging-test-with-rebase` circleCI check is failing due to changes in setuptools 46.0.0, with the error:
```
Creating Python 3 virtualenv in .venv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/sdci/securedrop-source/.venv/bin/python3
Also creating executable in /home/sdci/securedrop-source/.venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
    ERROR: Command errored out with exit status 1:
     command: /home/sdci/securedrop-source/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-916609ga/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-916609ga/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-916609ga/markupsafe/pip-egg-info
         cwd: /tmp/pip-install-916609ga/markupsafe/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-916609ga/markupsafe/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
```

## Steps to Reproduce

- Run CI.

## Expected Behavior

CI passes or fails for a valid reason.

## Actual Behavior

CI fails through no fault of the code.

**Comment by zenmonkeykstop** [comment]
Related setuptools issue: https://github.com/pypa/setuptools/issues/2017

**Comment by zenmonkeykstop** [comment]
We can probably just update markupsafe to fix this, trying that now...
