### ISSUE TITLE
`securedrop-admin setup` fails on Tails 4.4 (ImportError: cannot import name 'Feature')

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5155]
## Description

Attempting to run `./securedrop-admin setup` fails in Tails 4.4

## Steps to Reproduce

(Thanks to @conorsch for the write-up)
1. On an Admin Workstation running Tails 4.4, `cd ~/Persistent`
2. If you already have "securedrop" repo, move it aside, e.g. `mv securedrop{,.bak}`
3. Clone repo: `git clone https://github.com/freedomofpress/securedrop`
4. Hop into repo and check those tags: `cd securedrop && git tag -v 1.2.1 && git checkout 1.2.1`
5. Run setup (include -v flag for more verbose output): `./securedrop-admin setup -v`

## Expected Behavior

Setup completes successfully.

## Actual Behavior

Setup fails as follows:

```
[INFO] Examining package changes
[INFO] New packages manually installed: {'python3-virtualenv', 'python3-pip', 'libffi-dev', 'ccontrol', 'libpython3-dev', 'libssl-dev', 'virtualenv'}
INFO: Setting up virtualenv
DEBUG: b"Already using interpreter /usr/bin/python3\nUsing base prefix '/usr'\nNew python executable in /home/amnesia/Persistent/securedrop/admin/.venv3/bin/python3\nAlso creating executable in /home/amnesia/Persistent/securedrop/admin/.venv3/bin/python\nInstalling setuptools, pkg_resources, pip, wheel...done.\n"
INFO: Checking Python dependencies for securedrop-admin
DEBUG: b'Collecting ansible==2.7.13\n  Downloading ansible-2.7.13.tar.gz (11.9 MB)\nCollecting asn1crypto==0.24.0\n  Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)\nCollecting bcrypt==3.1.4\n  Downloading bcrypt-3.1.4.tar.gz (42 kB)\nCollecting cffi==1.11.4\n  Downloading cffi-1.11.4.tar.gz (436 kB)\nCollecting cryptography==2.7\n  Downloading cryptography-2.7-cp34-abi3-manylinux1_x86_64.whl (2.3 MB)\nCollecting jinja2==2.10.1\n  Downloading Jinja2-2.10.1-py2.py3-none-any.whl (124 kB)\nCollecting markupsafe==1.0\n  Downloading MarkupSafe-1.0.tar.gz (14 kB)\n    ERROR: Command errored out with exit status 1:\n     command: /home/amnesia/Persistent/securedrop/admin/.venv3/bin/python3 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-p3i4gd76/markupsafe/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-p3i4gd76/markupsafe/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' egg_info --egg-base /tmp/pip-install-p3i4gd76/markupsafe/pip-egg-info\n         cwd: /tmp/pip-install-p3i4gd76/markupsafe/\n    Complete output (5 lines):\n    Traceback (most recent call last):\n      File "<string>", line 1, in <module>\n      File "/tmp/pip-install-p3i4gd76/markupsafe/setup.py", line 6, in <module>\n        from setuptools import setup, Extension, Feature\n    ImportError: cannot import name \'Feature\' from \'setuptools\' (/home/amnesia/Persistent/securedrop/admin/.venv3/lib/python3.7/site-packages/setuptools/__init__.py)\n    ----------------------------------------\nERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\n'
ERROR: Failed to install pip dependencies. Check network connection and try again.
```

**Comment by eloquence** [comment]
First reported by @conorsch, I was able to reproduce. Appears to be the same issue with `markupsafe` as in #5150.

**Comment by redshiftzero** [comment]
cross linking #4686
