### ISSUE TITLE
`NoResultFound` error from sqlalchemy on `make dev` run

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop#5198]
Currently seeing the following on all `make dev` runs in `develop` (it starts fine regardless):

```
21:26:22 default: store.queued_add_checksum_for_file(<class 'models.Submission'>, 13, '/var/lib/securedrop/store/W7XCM6C4AFQDM7WJ2OQQ6AEULT3PFIMHZZDY6TCHCWKLSIOZGVCHLKJXMW42AHSWTJ3NUKRUHIS4TB4QN23OYVJMIKB4D2BFEF4R4AY=/1-tracheal_terminal-msg.gpg', 'sqlite:////var/lib/securedrop/db.sqlite') (a97d559b-13c2-4fa7-9953-c1abdbe1285f)
21:26:22 sqlalchemy.orm.exc.NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./store.py", line 375, in queued_add_checksum_for_file
    db_obj = session.query(db_model).filter_by(id=model_id).one()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3282, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/worker.py", line 822, in perform_job
    rv = job.perform()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 605, in perform
    self._result = self._execute()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/rq/job.py", line 611, in _execute
    return self.func(*self.args, **self.kwargs)
  File "./store.py", line 375, in queued_add_checksum_for_file
    db_obj = session.query(db_model).filter_by(id=model_id).one()
  File "/opt/venvs/securedrop-app-code/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3282, in one
    raise orm_exc.NoResultFound("No row was found for one()")
sqlalchemy.orm.exc.NoResultFound: No row was found for one()
2020-04-16 21:26:23,132 INFO Running every 60 seconds.
```

**Comment by eloquence** [comment]
After `make clean` repeat runs are fine, may have been an ephemeral local state issue. Closing.
