### ISSUE TITLE
securedrop_shredder, securedrop_source_deleter and  securedrop_rqrequeue is failing on Focal

### ISSUE THREAD

**Issue by kushaldas** [freedomofpress/securedrop#5522]
## Description

The following 3 services is not being able to start on Focal.

- securedrop_shredder
- securedrop_source_deleter
- securedrop_rqrequeue

## Steps to Reproduce

- [ ] `molecule converge -s libvirt-staging-focal`
- [ ] `molecule login -s libvirt-staging-focal -h app-staging`
- [ ] `journalctl -u securedrop_shredder.service`

## Expected Behavior

- [ ] No errors should be shown

## Actual Behavior

The service fails to start.

```
Sep 23 13:53:04 app-staging systemd[1]: Started SecureDrop shredder.
Sep 23 13:53:05 app-staging python[4711]: Traceback (most recent call last):
Sep 23 13:53:05 app-staging python[4711]:   File "/var/www/securedrop/scripts/shredder", line 18, in <module>
Sep 23 13:53:05 app-staging python[4711]:     import journalist_app
Sep 23 13:53:05 app-staging python[4711]:   File "/var/www/securedrop/journalist_app/__init__.py", line 4, in <module>
Sep 23 13:53:05 app-staging python[4711]:     from flask import (Flask, session, redirect, url_for, flash, g, request,
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
Sep 23 13:53:05 app-staging python[4711]:     from jinja2 import Markup, escape
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/jinja2/__init__.py", line 82, in <module>
Sep 23 13:53:05 app-staging python[4711]:     _patch_async()
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/jinja2/__init__.py", line 78, in _patch_async
Sep 23 13:53:05 app-staging python[4711]:     from jinja2.asyncsupport import patch_all
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/jinja2/asyncsupport.py", line 13, in <module>
Sep 23 13:53:05 app-staging python[4711]:     import asyncio
Sep 23 13:53:05 app-staging python[4711]:   File "/usr/lib/python3.8/asyncio/__init__.py", line 8, in <module>
Sep 23 13:53:05 app-staging python[4711]:     from .base_events import *
Sep 23 13:53:05 app-staging python[4711]:   File "/usr/lib/python3.8/asyncio/base_events.py", line 45, in <module>
Sep 23 13:53:05 app-staging python[4711]:     from . import staggered
Sep 23 13:53:05 app-staging python[4711]:   File "/usr/lib/python3.8/asyncio/staggered.py", line 6, in <module>
Sep 23 13:53:05 app-staging python[4711]:     import typing
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/typing.py", line 1347, in <module>
Sep 23 13:53:05 app-staging python[4711]:     class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
Sep 23 13:53:05 app-staging python[4711]:   File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/typing.py", line 1003, in __new__
Sep 23 13:53:05 app-staging python[4711]:     self._abc_registry = extra._abc_registry
Sep 23 13:53:05 app-staging python[4711]: AttributeError: type object 'Callable' has no attribute '_abc_registry'
Sep 23 13:53:05 app-staging systemd[1]: securedrop_shredder.service: Main process exited, code=exited, status=1/FAILURE
Sep 23 13:53:05 app-staging systemd[1]: securedrop_shredder.service: Failed with result 'exit-code'.

```

## Comments

Suggestions to fix, any other relevant information.

**Comment by kushaldas** [comment]
NOTE: just removing `typing` module from our virtual environment will all the 3 services. How to do that properly? We will have to find an answer for that.

**Comment by kushaldas** [comment]
Reason: The `typing` module is a backport of the same module from CPython itself, and we don't have a release yet for `Python3.8` which has the newest code on Focal.
