### ISSUE TITLE
Unhandled exception for short username in manage.py

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop#6188]
## Description

When attempting to add a < 3-letter username during `./manage.py add-admin` or `./manage.py add-journalist`, user encounters a python traceback instead of an easy-to-read error message.

## Steps to Reproduce

SSH to servers (I used staging) 
```
sudo -u www-data bash
cd /var/www/securedrop
./manage.py add-admin  # Try any 2-letter username
```

## Expected Behavior
A message that says "Sorry, please choose a username over 2 characters."

## Actual Behavior
```
www-data@app-staging:~/securedrop$ ./manage.py add-admin                                                 
Username: ab                                                                                             
Traceback (most recent call last):                                                                       
  File "./manage.py", line 425, in <module>                                                              
    _run_from_commandline()                                                                              
  File "./manage.py", line 415, in _run_from_commandline                                                 
    rc = args.func(args)                                                                                 
  File "./manage.py", line 125, in add_admin                                                             
    return _add_user(is_admin=True)                                                                      
  File "./manage.py", line 182, in _add_user                                                             
    username = _get_username()                      
  File "./manage.py", line 136, in _get_username                                                         
    Journalist.check_username_acceptable(username)                                                       
  File "/var/www/securedrop/models.py", line 504, in check_username_acceptable                           
    ngettext(             
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask_babel/__init__.py", line 573, in ngettext                 
    t = get_translations()                          
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask_babel/__init__.py", line 227, in get_translations         
    [get_locale()],       
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask_babel/__init__.py", line 257, in get_locale               
    rv = babel.locale_selector_func()               
  File "/var/www/securedrop/i18n.py", line 125, in <lambda>                                              
    babel.localeselector(lambda: get_locale(config))                                                     
  File "/var/www/securedrop/i18n.py", line 197, in get_locale                                            
    locale = session.get("locale")                  
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/werkzeug/local.py", line 348, in __getattr__                    
   return getattr(self._get_current_object(), name)                                                     
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/werkzeug/local.py", line 307, in _get_
current_object            
    return self.__local()                           
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/flask/globals.py", line 37, in _lookup
_req_object               
    raise RuntimeError(_request_ctx_err_msg)                                                             
RuntimeError: Working outside of request context. 
```

**Comment by nahara7** [comment]
Is this still a desired change ? I was able to get this to return the proper error messages, instead of the python traceback, by doing the following(In the developer environment): 
 * initializing an application and babel object in `models.py` 
  * using the app context [here](https://github.com/freedomofpress/securedrop/blob/b917f9c1e259d9e1d5220808bc9d1b2261f28012/securedrop/models.py#L520) to raise the InvalidUsernameExceptions.
  
  I'm happy to open a PR with my changes, but let me know a testing plan to attach !
