### ISSUE TITLE
Clean up manual sys.path additions in scripts

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6588]
*This is a good first issue for new contributors to take on, if you have any questions, please ask on the task or in our [Gitter room](https://gitter.im/freedomofpress/securedrop)!*

## Description

Our scripts have some manual `sys.path` additions that aren't actually needed:
```
$ rg sys.path securedrop/scripts -C 1
securedrop/scripts/rqrequeue
8-
9:sys.path.insert(0, "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages")  # noqa: E402
10:sys.path.insert(0, "/var/www/securedrop")  # noqa: E402
11-

securedrop/scripts/shredder
11-
12:sys.path.insert(0, ".")  # noqa: E402
13:sys.path.insert(
14-    0, "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages"
15-)  # noqa: E402
16:sys.path.insert(0, "/var/www/securedrop")  # noqa: E402
17-

securedrop/scripts/source_deleter
11-
12:sys.path.insert(0, ".")  # noqa: E402
13:sys.path.insert(
14-    0, "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages"
15-)  # noqa: E402
16:sys.path.insert(0, "/var/www/securedrop")  # noqa: E402
17-
```

There's no point in adding `.` to the path because it's already part of the lookup path by default. And the site-packages directory is already added by the virtualenv, so it's unnecessary too. We do need to keep the `/var/www/securedrop` one though.

**Comment by rahulXs** [comment]
Hi, I would like to work on this issue. Could you please assign it to me? Thanks!

**Comment by legoktm** [comment]
Done, let us know if you have any questions or issues!

**Comment by rahulXs** [comment]
@legoktm I've raised the PR #6589 for this issue. Please help to review.
I didn't fill the PR template checklist completely because few points (test plan, docs changes required) were not clear to me. Please let me know if any change is required. Thanks!

**Comment by legoktm** [comment]
I made a mistake, it works fine in production systems but breaks in the dev environment :/
```
Traceback (most recent call last):
  File "/home/user/github/freedomofpress/securedrop/securedrop/scripts/shredder", line 14, in <module>
    import journalist_app
ModuleNotFoundError: No module named 'journalist_app'
Traceback (most recent call last):
  File "/home/user/github/freedomofpress/securedrop/securedrop/scripts/source_deleter", line 14, in <module>
    import journalist_app
ModuleNotFoundError: No module named 'journalist_app'
```

Debugging why, but we should just make the dev environment more like how the systemd services are run.

**Comment by legoktm** [comment]
Looking at this again, I think we should aim to remove the final `sys.path.insert(0, "/var/www/securedrop")` in the scripts and instead rely on the systemd units that add `Environment=PYTHONPATH="/var/www/securedrop:..."`.

I *also* think we can remove `/opt/venvs/securedrop-app-code/lib/python3.8/site-packages` from the PYTHONPATH in the systemd units since we're invoking them with the `python` in the venv, it should already add the site-packages path to the PYTHONPATH.

I'm going to remove "good first issue" from this since I think it mostly needs someone to fiddle with this on a staging/production instance, thanks for the initial work you did on this @rahulXs, it's appreciated!
