### ISSUE TITLE
enable automatically-generated "pseudolocale"

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop#6690]
<https://github.com/freedomofpress/securedrop/issues/6380#issuecomment-1135240576>:

> Why are these omissions so difficult to catch during manual testing in the [string-freeze process](https://docs.securedrop.org/en/stable/development/i18n.html#two-weeks-before-the-release-string-freeze)? At that point in the localization cycle, _strings not (or incorrectly) marked for translation_ are indistinguishable from _strings not yet translated_.

We could solve this problem at least for human eyes by turning on Weblate's ["pseudolocale generation"](https://docs.weblate.org/en/latest/admin/addons.html#pseudolocale-generation):

> Pseudolocales are useful to find strings that are not prepared for localization. This is done by altering all translatable source strings to make it easy to spot unaltered strings when running the application in the pseudolocale language.

_Originally posted by @cfm in https://github.com/freedomofpress/securedrop/issues/6380#issuecomment-1302877526_

---

## Testing

In `freedomofpress/securedrop-i18n-sandbox` from `weblate-sandbox.securedrop.org`:
1. [x] Pseudolocale defined: https://weblate-sandbox.securedrop.org/projects/securedrop/securedrop/eo/
2. [x] Pseudolocale generation configured
3. [x] Pseudolocale can be added manually to `securedrop/i18n.json`
4. [x] Under `make dev`, pseudolocale can be selected in Source and Journalist Interfaces

## Production

In `freedomofpress/securedrop-i18n` from `weblate.securedrop.org`:

- [x] Replicate above configuration: https://weblate.securedrop.org/projects/securedrop/securedrop/eo/
- [x] Document use in QA:  https://github.com/freedomofpress/securedrop/wiki/QA-Procedures#localization-qa
- [x] Update freedomofpress/securedrop-client#1598

**Comment by cfm** [comment]
I've configured the "pseudolocale generation" add-on at `weblate-sandbox.securedrop.org` with these settings per [Weblate](https://docs.weblate.org/en/weblate-4.14/admin/addons.html#pseudolocale-generation) and [Microsoft](https://learn.microsoft.com/en-us/globalization/methodology/pseudolocalization) recommendations:

| Setting | Value |
| --- | --- |
| Source strings | English |
| Fixed string prefix | `[` |
| Variable string prefix | `!` |
| Fixed string suffix | `]` |
| Variable string suffix | `!` |
| Variable part multiplier | `0.1` |

For the **Target language** setting, I tried both Weblate's [recommended](https://github.com/WeblateOrg/weblate/issues/5164) `en_XA` and a [custom "unknown" locale `und_US`](https://weblate-sandbox.securedrop.org/admin/lang/language/628/change/).  Even once added in `securedrop/i18n.json`, neither is usable by Babel because neither is present in the Unicode Common Locale Data Repository:

```python
>>> import babel
>>> babel.Locale.parse('en_XA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/securedrop/.venv/lib/python3.9/site-packages/babel/core.py", line 330, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'en_XA'
>>> babel.Locale.parse('und_US')
Locale('en', territory='US')  # collides with real en_US
```

We ran into a version of this problem in #6406, where under test we cheekily defined:

https://github.com/freedomofpress/securedrop/blob/9c119506a9f9a67929491ad79011bcb323cec39e/securedrop/tests/test_i18n.py#L43

I'll have to think more about this.

**Comment by cfm** [comment]
Having tried `en_devel` in addition to `en_XA` and `und_US`, we'll have to use `NEVER_LOCALE = 'eo'` after all, at least until Babel supports custom locales (python-babel/babel#454).  I've created [`eo`](https://weblate.securedrop.org/projects/securedrop/securedrop/eo/) in production Weblate, configured the "Pseudolocale Generation" add-on, and documented how to use `eo` in QA in <https://github.com/freedomofpress/securedrop/wiki/QA-Procedures#localization-qa>.
