### ISSUE TITLE
`make build-debs` is exiting with 0 status code even on failure

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6858]
## Description

`make build-debs` is exiting with a 0 status code, even when it fails.

## Steps to Reproduce

1. Check out the broken version of #6855.
2. `make build-debs`

## Expected Behavior

dpkg-buildpackage failure should bubble up

## Actual Behavior

```
...
Failed to build cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/usr/bin/dh_virtualenv", line 111, in <module>
    sys.exit(main() or 0)
  File "/usr/bin/dh_virtualenv", line 91, in main
    deploy.install_dependencies()
  File "/usr/lib/python3/dist-packages/dh_virtualenv/deployment.py", line 202, in install_dependencies
    subprocess.check_call(self.pip('-r', requirements_path))
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/srv/securedrop/debian/securedrop-app-code/opt/venvs/securedrop-app-code/bin/python', '/srv/securedrop/debian/securedrop-app-code/opt/venvs/securedrop-app-code/bin/pip', 'install', '--log=/tmp/tmpi5yh1c18', '--verbose', '--no-deps', '--no-binary=:all:', '--no-cache-dir', '-r', './requirements.txt']' returned non-zero exit status 1.
make[1]: *** [debian/rules:40: override_dh_virtualenv] Error 1
make[1]: Leaving directory '/srv/securedrop'
make: *** [debian/rules:7: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
Script done.

You can now examine or commit the log at:
/home/user/github/freedomofpress/securedrop/build/20231616-securedrop.log
user@dev ~/g/f/securedrop> echo $status
0
```

## Comments

Probably a regression from the script handling?

**Comment by legoktm** [comment]
Per [`script(1)`](https://manpages.debian.org/bookworm/bsdutils/script.1.en.html) we need to pass the `--return` flag
