### ISSUE TITLE
make dev failing with GNUPG error

### ISSUE THREAD

**Issue by chamalis** [freedomofpress/securedrop#6899]
I have the same issue with #5961 which persists after "docker prunes" and reboots.

The issue seems to be that the `using_keys_with_fingerprints` passed down to [EncryptionManager._encrypt](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/encryption.py#L186) function, during the test data creation, is the default value in [config.py ](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/config.py.example#L42)(enclosed in a list of course): `['{{securedrop_app_gpg_fingerprint}}']`

```
$ make dev
 
#0 building with "default" instance using docker driver

#1 [internal] load build definition from SlimDockerfile
#1 transferring dockerfile: 2.57kB done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 88B done
#2 DONE 0.1s

#3 [internal] load metadata for docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd
#3 DONE 1.4s

#4 [internal] load build context
#4 transferring context: 113.98kB 0.0s done
#4 DONE 0.1s

#5 [1/7] FROM docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd
#5 resolve docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd 0.0s done

.... trimmed ...

#6 [2/7] RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y                        apache2-dev coreutils vim                        python3-pip python3-all python3-venv virtualenv python3-dev libssl-dev                        gnupg2 redis-server git curl wget                        enchant libffi-dev sqlite3 gettext sudo tor basez pkg-config
#6 0.486 Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]

... trimmed ...

#7 [3/7] RUN TMPDIR=`mktemp -d` && cd ${TMPDIR}         && curl --proto '=https' --tlsv1.2 -OO -sSf https://static.rust-lang.org/rustup/archive/1.24.3/x86_64-unknown-linux-gnu/rustup-init         && echo "3dc5ef50861ee18657f9db2eeb7392f9c2a6c95c90ab41e45ab4ca71476b4338 *rustup-init" | sha256sum -c -         && chmod +x rustup-init         && ./rustup-init --default-toolchain=1.69.0 --profile minimal -y         && cd && rm -rf ${TMPDIR}
#7 19.44 rustup-init: OK
#7 19.49 info: profile set to 'minimal'
#7 19.49 info: default host triple is x86_64-unknown-linux-gnu
#7 19.49 info: syncing channel updates for '1.69.0-x86_64-unknown-linux-gnu'
#7 20.34 info: latest update on 2023-04-20, rust version 1.69.0 (84c898d65 2023-04-16)
#7 20.34 info: downloading component 'cargo'
#7 21.65 info: downloading component 'rust-std'
#7 28.11 info: downloading component 'rustc'
#7 40.23 info: installing component 'cargo'
#7 40.77 info: installing component 'rust-std'
#7 42.68 info: installing component 'rustc'
#7 46.38 info: default toolchain set to '1.69.0-x86_64-unknown-linux-gnu'
#7 46.38 
#7 46.40   1.69.0-x86_64-unknown-linux-gnu installed - rustc 1.69.0 (84c898d65 2023-04-16)
#7 46.40 
#7 46.40 
#7 46.40 Rust is installed now. Great!
#7 46.40 
#7 46.40 To get started you may need to restart your current shell.
#7 46.40 This would reload your PATH environment variable to include
#7 46.40 Cargo's bin directory (/opt/cargo/bin).
#7 46.40 
#7 46.40 To configure your current shell, run:
#7 46.40 source /opt/cargo/env
#7 DONE 47.1s

#8 [4/7] COPY requirements requirements
#8 DONE 0.1s

#9 [5/7] RUN python3 -m venv /opt/venvs/securedrop-build &&     /opt/venvs/securedrop-build/bin/pip3 install --no-deps --require-hashes -r requirements/python3/build-requirements.txt
#9 2.727 Collecting maturin==1.0.1
#9 2.917   Downloading maturin-1.0.1-py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.musllinux_1_1_x86_64.whl (9.6 MB)
#9 5.601 Collecting tomli==2.0.1
#9 5.654   Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
#9 5.673 Installing collected packages: maturin, tomli
#9 5.843 Successfully installed maturin-1.0.1 tomli-2.0.1
#9 DONE 5.9s

#10 [6/7] RUN python3 -m venv /opt/venvs/securedrop-app-code &&     /opt/venvs/securedrop-app-code/bin/pip3 install --no-deps --require-hashes -r requirements/python3/bootstrap-requirements.txt &&     /opt/venvs/securedrop-app-code/bin/pip3 install --no-deps --require-hashes -r requirements/python3/test-requirements.txt &&     /opt/venvs/securedrop-app-code/bin/pip3 install --no-deps --require-hashes -r requirements/python3/requirements.txt
#10 2.365 Collecting setuptools-scm==6.0.1
#10 2.537   Downloading setuptools_scm-6.0.1-py3-none-any.whl (27 kB)

...  trimmed ...


#11 [7/7] RUN if test user != root ; then useradd --no-create-home --home-dir /tmp --uid 1000 user && echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers ; fi &&     chown -R user.user /opt/venvs/
#11 DONE 42.6s

#12 exporting to image
#12 exporting layers
#12 exporting layers 2.7s done
#12 writing image sha256:05fa0502d34c0e4d64a1e44aacae51236c051b4f142633ccae8a34163090a0d9 done
#12 naming to docker.io/library/securedrop-slim-focal-py3 0.0s done
#12 DONE 2.7s
************************************************************
Exposed services will be available on localhost at
Source interface: http://127.0.0.1:8080
Journalist interface: http://127.0.0.1:8081
************************************************************
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at /opt/venvs/securedrop-app-code/bin/python3
📡 Using build options compatibility from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
📖 Found type stub file at redwood.pyi
📦 Built wheel for CPython 3.8 to /home/user/code/fop/sdrop/securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Processing /home/user/code/fop/sdrop/securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: redwood
Successfully installed redwood-0.1.0
WARNING: You are using pip version 21.1.1; however, version 23.2.1 is available.
You should consider upgrading via the '/opt/venvs/securedrop-app-code/bin/python3 -m pip install --upgrade pip' command.
main: /var/lib/securedrop/db.sqlite
gpg: keybox '/var/lib/securedrop/keys/pubring.gpg' created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: Total number processed: 1
gpg:               imported: 1
Created journalist (username=journalist, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=True)
Created journalist (username=dellsberg, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Traceback (most recent call last):
  File "./loaddata.py", line 460, in <module>
    load(parse_arguments())
  File "./loaddata.py", line 379, in load
    add_sources(args, journalists)
  File "./loaddata.py", line 332, in add_sources
    submit_message(source, secrets.choice(journalists) if seen_message_count > 0 else None)
  File "./loaddata.py", line 181, in submit_message
    fpath = Storage.get_default().save_message_submission(
  File "/home/user/code/fop/sdrop/securedrop/securedrop/store.py", line 376, in save_message_submission
    EncryptionManager.get_default().encrypt_source_message(
  File "/home/user/code/fop/sdrop/securedrop/securedrop/encryption.py", line 138, in encrypt_source_message
    self._encrypt(
  File "/home/user/code/fop/sdrop/securedrop/securedrop/encryption.py", line 192, in _encrypt
    raise GpgEncryptError(out.stderr)
encryption.GpgEncryptError: [GNUPG:] FAILURE option-parser 33554433
gpg: missing argument for option "--recipient"

make: *** [Makefile:239: dev] Error 1
```

If I hardcode the fingerprint (`CC40FF1228271441`) of `securedrop/securedrop/tests/files/test_journalist_key.pub `, like this (or change it in `config.py`):
```python
    def _encrypt(
        self,
        using_keys_with_fingerprints: List[str],
        plaintext_in: typing.IO,
        ciphertext_path_out: Path,
    ) -> None:
        # Remove any spaces from provided fingerprints GPG outputs fingerprints
        # with spaces for readability, but requires the spaces to be removed
        # when using fingerprints to specify recipients.
        sanitized_key_fingerprints = [fpr.replace(" ", "") for fpr in using_keys_with_fingerprints]

        out = self._gpg.encrypt(
            plaintext_in,
            'CC40FF1228271441',  # *sanitized_key_fingerprints,
            output=str(ciphertext_path_out),
            always_trust=True,
            armor=False,
        )
        if not out.ok:
            raise GpgEncryptError(out.stderr)
```
the issue turns to:
`encryption.GpgEncryptError: gpg: CC40FF1228271441: skipped: No public key`, 
despite the fact that it seems to have already been imported:

```
export DOCKER_BUILD_VERBOSE=true
(sdrop) user@hostname:~/path_to_securedrop$ make dev
███ Starting development server...
[+] Building 276.8s (12/12) FINISHED                                                                                     docker:default
 => [internal] load build definition from SlimDockerfile                                                                           0.0s
 => => transferring dockerfile: 2.57kB                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                  0.0s
 => => transferring context: 88B                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd  2.7s
 => [1/7] FROM docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                    6.3s
 => => resolve docker.io/library/ubuntu@sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd                    0.0s
 => => sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83 28.58MB / 28.58MB                                   5.6s
 => => sha256:450e066588f42ebe1551f3b1a535034b6aa46cd936fe7f2c6b0d72997ec61dbd 1.42kB / 1.42kB                                     0.0s
 => => sha256:b25ef49a40b7797937d0d23eca3b0a41701af6757afca23d504d50826f0b37ce 529B / 529B                                         0.0s
 => => sha256:680e5dfb52c74a1fbc99c2922c8e25b5736e6cd1a3d9430890d52a4f8f44087a 1.46kB / 1.46kB                                     0.0s
 => => extracting sha256:eaead16dc43bb8811d4ff450935d607f9ba4baffda4fc110cc402fa43f601d83                                          0.5s
 => [internal] load build context                                                                                                  0.0s
 => => transferring context: 113.98kB                                                                                              0.0s
 => [2/7] RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y                        apache2-dev  118.0s
 => [3/7] RUN TMPDIR=`mktemp -d` && cd ${TMPDIR}         && curl --proto '=https' --tlsv1.2 -OO -sSf https://static.rust-lang.or  64.2s
 => [4/7] COPY requirements requirements                                                                                           0.0s 
 => [5/7] RUN python3 -m venv /opt/venvs/securedrop-build &&     /opt/venvs/securedrop-build/bin/pip3 install --no-deps --require  8.2s 
 => [6/7] RUN python3 -m venv /opt/venvs/securedrop-app-code &&     /opt/venvs/securedrop-app-code/bin/pip3 install --no-deps --  59.5s 
 => [7/7] RUN if test user != root ; then useradd --no-create-home --home-dir /tmp --uid 1000 user && echo "user ALL=(ALL) NOPAS  14.7s 
 => exporting to image                                                                                                             3.1s 
 => => exporting layers                                                                                                            3.1s 
 => => writing image sha256:ec5fe5ef92061bb9b7f47e33af7edd651cc72655d071770cee0d6565d255f04f                                       0.0s 
 => => naming to docker.io/library/securedrop-slim-focal-py3                                                                       0.0s 
************************************************************                                                                            
Exposed services will be available on localhost at
Source interface: http://127.0.0.1:8080
Journalist interface: http://127.0.0.1:8081
************************************************************
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at /opt/venvs/securedrop-app-code/bin/python3
📡 Using build options compatibility from pyproject.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
📖 Found type stub file at redwood.pyi
📦 Built wheel for CPython 3.8 to /home/user/path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Processing /home/user/path_to_securedrop/target/dev/wheels/redwood-0.1.0-cp38-cp38-linux_x86_64.whl
Installing collected packages: redwood
Successfully installed redwood-0.1.0
WARNING: You are using pip version 21.1.1; however, version 23.2.1 is available.
You should consider upgrading via the '/opt/venvs/securedrop-app-code/bin/python3 -m pip install --upgrade pip' command.
main: /var/lib/securedrop/db.sqlite
gpg: keybox '/var/lib/securedrop/keys/pubring.gpg' created
gpg: key CC40EF1228271441: public key "SecureDrop Test/Development (DO NOT USE IN PRODUCTION)" imported
gpg: Total number processed: 1
gpg:               imported: 1
Created journalist (username=journalist, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=True)
Created journalist (username=dellsberg, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Created journalist (username=clarkkent, password=correct horse battery staple profanity oil chewy, otp_secret=JHCOGO7VCER3EJ4L, is_admin=False)
Traceback (most recent call last):
  File "./loaddata.py", line 460, in <module>
    load(parse_arguments())
  File "./loaddata.py", line 379, in load
    add_sources(args, journalists)
  File "./loaddata.py", line 332, in add_sources
    submit_message(source, secrets.choice(journalists) if seen_message_count > 0 else None)
  File "./loaddata.py", line 181, in submit_message
    fpath = Storage.get_default().save_message_submission(
  File "/home/user/path_to_securedrop/securedrop/store.py", line 376, in save_message_submission
    EncryptionManager.get_default().encrypt_source_message(
  File "/home/user/path_to_securedrop/securedrop/encryption.py", line 138, in encrypt_source_message
    self._encrypt(
  File "/home/user/path_to_securedrop/securedrop/encryption.py", line 192, in _encrypt
    raise GpgEncryptError(out.stderr)
encryption.GpgEncryptError: gpg: CC40FF1228271441: skipped: No public key
[GNUPG:] INV_RECP 1 CC40FF1228271441
[GNUPG:] FAILURE encrypt 9
gpg: [stdin]: encryption failed: No public key

make: *** [Makefile:239: dev] Error 1
```

_Originally posted by @chamalis in https://github.com/freedomofpress/securedrop/issues/5961#issuecomment-1653352123_

**Comment by legoktm** [comment]
Hi @chamalis, thanks for reporting this (and trying out SecureDrop). I've never seen this before and am a bit stumped on what would cause this given we can see the key being imported into the keyring...maybe in self._encrypt() you can add `print(self._gpg.list_keys())` so see what it thinks is in the keyring?

What OS, etc. are you running this on? 

Also note that this code is all being significantly refactored/rewritten in #6892, so I don't want to waste your time debugging something that's going to go away in a few weeks.

> The issue seems to be that the using_keys_with_fingerprints passed down to [EncryptionManager._encrypt](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/encryption.py#L186) function, during the test data creation, is the default value in [config.py ](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/config.py.example#L42)(enclosed in a list of course): ['{{securedrop_app_gpg_fingerprint}}']

Huh, so it's also not creating config.py correctly? Are there other templated values that weren't replaced?

**Comment by chamalis** [comment]
Hi @legoktm , thanks for the prompt reply :)

- My bad. I forgot the obvious:

```bash
$ uname -a
Linux hostname 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
$
$ docker --version
Docker version 24.0.4, build 3713ee1
```

- Here is the keyring as returned inside `_encrypt()`:
```bash
[{'type': 'pub', 'trust': '-', 'length': '4096', 'algo': '1', 'keyid': 'CC40EF1228271441', 'date': '1381600096', 'expires': '', 'dummy': '', 'ownertrust': '-', 'uids': ['SecureDrop Test/Development (DO NOT USE IN PRODUCTION)'], 'sigs': {'SecureDrop Test/Development (DO NOT USE IN PRODUCTION)': []}, 'rev': {}, 'subkeys': [['C3E7C4C0A2201B2A', 'e']], 'fingerprint': 'C1C4E16BB24E4F4ABF37C3A6C3E7C4C0A2201B2A'}, {'type': 'pub', 'trust': 'u', 'length': '4096', 'algo': '1', 'keyid': 'DD932F1B6F13C94F', 'date': '1368489600', 'expires': '', 'dummy': '', 'ownertrust': 'u', 'uids': ['Source Key <TDXFUHDT622HWMT257KL733VRUWNTQWHN3IIPI6Z2QGY374K53KMSYJHTNJFTKHSIGNMQ4CBZSRPIRY5MWZ5J72PHUFMUERLEZY3PZQ=>'], 'sigs': {'Source Key <TDXFUHDT622HWMT257KL733VRUWNTQWHN3IIPI6Z2QGY374K53KMSYJHTNJFTKHSIGNMQ4CBZSRPIRY5MWZ5J72PHUFMUERLEZY3PZQ=>': []}, 'rev': {}, 'subkeys': [], 'fingerprint': '3266D8FA9191C7BD86C8FAC1DD932F1B6F13C94F'}]
```

- config.py is created on the host under `./securedrop/` with the following contents:
```python
import os

# Default values for production, may be overridden later based on environment
class FlaskConfig:
    DEBUG = False
    MAX_CONTENT_LENGTH = 524288000
    TESTING = False
    USE_X_SENDFILE = False
    WTF_CSRF_ENABLED = True

# Use different secret keys for the two different applications so their
# sessions can't be confused.
class SourceInterfaceFlaskConfig(FlaskConfig):
    SECRET_KEY = '{{ source_secret_key.stdout }}'
    SESSION_COOKIE_NAME = "ss"

class JournalistInterfaceFlaskConfig(FlaskConfig):
    SECRET_KEY = '{{ journalist_secret_key.stdout }}'
    SESSION_COOKIE_NAME = "js"

# These files are in the same directory as config.py. Use absolute paths to
# avoid potential problems with the test runner - otherwise, you have to be in
# this directory when you run the code.
SECUREDROP_ROOT = os.path.dirname(os.path.realpath(__file__))

SOURCE_TEMPLATES_DIR = os.path.join(SECUREDROP_ROOT, 'source_templates')
JOURNALIST_TEMPLATES_DIR = os.path.join(SECUREDROP_ROOT, 'journalist_templates')
WORD_LIST = os.path.join(SECUREDROP_ROOT, 'wordlist')
NOUNS = os.path.join(SECUREDROP_ROOT, 'dictionaries/nouns.txt')
ADJECTIVES = os.path.join(SECUREDROP_ROOT, './dictionaries/adjectives.txt')

WORKER_PIDFILE = "/tmp/securedrop_worker.pid"

# "head -c 32 /dev/urandom | base64" for constructing public ID from source codename
SCRYPT_ID_PEPPER = '{{ scrypt_id_pepper.stdout }}'
# "head -c 32 /dev/urandom | base64" for stretching source codename into GPG passphrase
SCRYPT_GPG_PEPPER = '{{ scrypt_gpg_pepper.stdout }}'
SCRYPT_PARAMS = dict(N=2**14, r=8, p=1)

# Fingerprint of the public key to use for encrypting submissions
# Defaults to test_journalist_key.pub, which is used for development and testing
JOURNALIST_KEY = '{{ securedrop_app_gpg_fingerprint }}'

# Directory where SecureDrop stores the database file, GPG keyring, and
# encrypted submissions.
SECUREDROP_DATA_ROOT = '/var/lib/securedrop'

# Modify configuration for alternative environments
env = os.environ.get('SECUREDROP_ENV') or 'prod'

if env == 'prod':
    # This is recommended for performance, and also resolves #369
    FlaskConfig.USE_X_SENDFILE = True
elif env == 'dev':
    # Enable Flask's debugger for development
    FlaskConfig.DEBUG = True
    # Use MAX_CONTENT_LENGTH to mimic the behavior of Apache's LimitRequestBody
    # in the development environment. See #1714.
    FlaskConfig.MAX_CONTENT_LENGTH = 524288000
elif env == 'test':
    FlaskConfig.TESTING = True
    # Disable CSRF checks to make writing tests easier
    FlaskConfig.WTF_CSRF_ENABLED = False
    SECUREDROP_DATA_ROOT = '/tmp/securedrop'

# The following configuration is dependent on SECUREDROP_DATA_ROOT

# Directory where encrypted submissions are stored
STORE_DIR=os.path.join(SECUREDROP_DATA_ROOT, 'store')

# Directory where GPG keyring is stored
GPG_KEY_DIR=os.path.join(SECUREDROP_DATA_ROOT, 'keys')

# Directory for temporary files
# We use a directory under the SECUREDROP_DATA_ROOT instead of `/tmp` because
# we need to expose this directory via X-Send-File, and want to minimize the
# potential for exposing unintended files.
TEMP_DIR = os.path.join(SECUREDROP_DATA_ROOT, "tmp")

# Database configuration
DATABASE_ENGINE = 'sqlite'
DATABASE_FILE = os.path.join(SECUREDROP_DATA_ROOT, 'db.sqlite')

# Which of the available locales should be displayed by default ?
DEFAULT_LOCALE = 'en_US'

# How long a session is valid before it expires and logs a user out
SESSION_EXPIRATION_MINUTES = 120
```

- Yes, by adding the following code:

```python
sdconf = SecureDropConfig.get_current()
attrs = [(a, getattr(sdconf, a)) if not callable(getattr(sdconf, a)) else ('', '') for a in dir(sdconf)]
```

in `EncryptionManager.get_default` and `EncryptionManager._encrypt`,
I can spot some more template values:

```
SCRYPT_GPG_PEPPER: {{ scrypt_gpg_pepper.stdout }}
SCRYPT_ID_PEPPER: {{ scrypt_id_pepper.stdout }}
all_the SECRET_KEY='{{ journalist_secret_key.stdout }}    # also: '{{ source_secret_key.stdout }}'
```

which I noticed that are the exact constants directly accessed / not parsed, in [_parse_config_from_file:194](https://github.com/freedomofpress/securedrop/blob/2bc42f09f7cc132d55f5ba0c12d277550f3c164a/securedrop/sdconfig.py#L194)

Thanks a lot for the #6892 mention, because I had indeed started trying to contribute something here :D

**Comment by legoktm** [comment]
@chamalis what if you delete `securedrop/config.py` and then try to run `make dev`?

If that doesn't work, what does `make test-config` do?

(my current theory is that the gpg issues are a symptom and the real issue is somewhere closer to config.py being incorrectly generated...)

**Comment by chamalis** [comment]
@legoktm Indeed, it was that simple! Removing `config.py` worked, thanks!

**Comment by legoktm** [comment]
ok, awesome! I'm going to close this now but let me/us know if you run into any other issues.
