### ISSUE TITLE
17c559a7a685_pgp_public_keys.py fails on fresh installs and breaks staging builds

### ISSUE THREAD

**Issue by legoktm** [freedomofpress/securedrop#6976]
## Description

The newly added migration to export public keys out of the GPG keyring is failing on fresh installs and breaks the CI staging build.

## Steps to Reproduce

Do a staging build

## Expected Behavior

It installs SecureDrop

## Actual Behavior

Via <https://app.circleci.com/pipelines/github/freedomofpress/securedrop/6375/workflows/ed03fa6e-3ada-4e59-ba88-1aed7e85fef6/jobs/72408> (h/t to @cfm for noticing)

```
INFO  [alembic.runtime.migration] Running upgrade 811334d7105f -> 17c559a7a685, PGP public keys
Traceback (most recent call last):
  File "/opt/venvs/securedrop-app-code/bin/alembic", line 33, in <module>
    sys.exit(load_entry_point('alembic==0.9.9', 'console_scripts', 'alembic')())
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/config.py", line 486, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/config.py", line 480, in main
    self.run_cmd(cfg, options)
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/config.py", line 461, in run_cmd
    fn(config,
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/util/compat.py", line 83, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/securedrop/alembic/env.py", line 82, in <module>
    run_migrations_online()
  File "/var/www/securedrop/alembic/env.py", line 76, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/venvs/securedrop-app-code/lib/python3.8/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/var/www/securedrop/alembic/versions/17c559a7a685_pgp_public_keys.py", line 35, in upgrade
    config = SecureDropConfig.get_current()
  File "/var/www/securedrop/sdconfig.py", line 94, in get_current
    _current_config = _parse_config_from_file(config_module_name="config")
  File "/var/www/securedrop/sdconfig.py", line 103, in _parse_config_from_file
    config_from_local_file = import_module(config_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config
```

## Comments

Other migrations that need to access config have a guard like:
```
# raise the errors if we're not in production
raise_errors = os.environ.get("SECUREDROP_ENV", "prod") != "prod"

try:
    from journalist_app import create_app
    from models import Reply, Submission
    from sdconfig import SecureDropConfig
    from store import Storage, queued_add_checksum_for_file
    from worker import create_queue
except:  # noqa
    if raise_errors:
        raise
```

But IMO this is excessive and we should just do what we actually need, of guarding the "config" import.

Also we should have a variant of the alembic tests that perform the migration without config.py present so it would get caught by an app-test run.

**Comment by legoktm** [comment]
> But IMO this is excessive and we should just do what we actually need, of guarding the "config" import.

In fact, this analysis was wrong. Importing sdconfig is perfectly fine, it's `SecureDropConfig.get_current()` that will throw if no config.py is present.
