### ISSUE TITLE
Functional tests broken in local development environment

### ISSUE THREAD

**Issue by garrettr** [freedomofpress/securedrop#988]
# STR

```sh
vagrant destroy -f development && vagrant up development
vagrant ssh
cd /vagrant/securedrop
./manage.py test
```

**Expected Result:** The full test suite runs and all tests pass.

**Actual Result:** The functional tests error out with the following traceback:

```
test_submit_and_retrieve_happy_path (tests.functional.submit_and_retrieve_message.SubmitAndRetrieveMessage) ...  * Running on http://127.0.0.1:50827/
 * Running on http://127.0.0.1:46191/
ERROR

======================================================================
ERROR: test_submit_and_retrieve_happy_path (tests.functional.submit_and_retrieve_message.SubmitAndRetrieveMessage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/functional/submit_and_retrieve_message.py", line 15, in setUp
    functional_test.FunctionalTest.setUp(self)
  File "tests/functional/functional_test.py", line 82, in setUp
    self.driver = self._create_webdriver()
  File "tests/functional/functional_test.py", line 46, in _create_webdriver
    return webdriver.Firefox(firefox_binary=firefox)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 66, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 105, in _wait_until_connectable
    raise WebDriverException("Can't load the profile. Profile "
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 1 test in 30.725s

FAILED (errors=1)
```

**Comment by garrettr** [comment]
This issue is due to the Selenium Python package needing to be upgraded to work with the latest stable version of Firefox. When I run `sudo pip install -U selenium` on the development VM to upgrade Selenium from 2.44.0 to 2.45.0, the functional tests work again.
